### ISSUE TITLE
Grunes Tal Update Check list

### ISSUE THREAD

**Issue by Heathendel** [rockfireredmoon/iceee#10]
So with essentially everything finished for Grunes Tal I figured I'd post a check list that you can reference to make sure nothings left out, but before that ill post the items for Folkirk and Grunes Tal.

~~Em - Added to data (not in a chest yet)~~

Item ID: 10002
~~Essence Gear for The Wailer : ~~
~~Essence of the Wailer~~
~~lvl 48 Epic~~

Item ID: 10003
~~Amulet Knight Str 20~~
~~Con 10~~
~~Physical Crit 2.5%~~

Item ID: 10004
~~Amulet Rogue Dex 20~~
~~Con 10~~
~~Attackspeed Increase 2.5%~~

Item ID: 10005
~~Amulet Druid Spi 20~~
~~Con 10~~
~~Castrate increase 2.5%~~

~~Amulet Mage Psy 20~~
~~Con 10~~
~~Magic Crit 2.5%~~

These are next ones are item designs that need stats still.

Father Grundy Essence Gear:

Item ID: 10006 - Grundy's Organic Hammer 
~~1H meathunk: c2:{["a"]=[{["type"]="Item-Leg_of_Meat",["node"]="right_hand",["colors"]=["0D233F","2A0000"]}],["c"]={["boots"]={["type"]="Armor-Cloth-Low1",["colors"]=["6a60a5","7c6ba2","e8af5e","6e85bb"]},["chest"]={["type"]="Armor-Cloth-Mid5",["colors"]=["55467f","552c26","a5a19c","d29e6f","6c6c6c"]},["leggings"]={["type"]="Armor-Cloth-Mid4",["colors"]=["9c80e9","f6c52e","cd901f","a74755","cfa43c"]},["belt"]={["type"]="Armor-Cloth-Low1",["colors"]=["a74755","7c6ba2","e8af5e","6e85bb"]},["collar"]={["type"]="Armor-Cloth-Low1",["colors"]=["f6c52e","f6c52e","e8af5e","f6c52e"]},["arms"]={["type"]="Armor-Cloth-Low1",["colors"]=["6a60a5","7c6ba2","e8af5e","6e85bb"]}},["b"]="n",["sk"]={["hands_feet"]="949494",["eye_white"]="FFFFFF",["nails"]="56514A",["mask"]="949494",["base"]="949494",["inner_ear"]="949494",["eye"]="1B9438",["head_highlight"]="949494",["nose"]="949494",["chest"]="949494"},["sz"]="1",["h"]=0,["g"]="m",["r"]="g"}~~

Item ID: 10007 - Grundys head band:
~~Grundys head band: c2:{["a"]=[{["type"]="Armor-Light-Low3-Helmet",["node"]="hat",["colors"]=["1F6A24","946624","944D0D","0A5503"]}],["c"]={["collar"]={["type"]="Armor-Medium-Low1",["colors"]=[]}},["b"]="n",["sk"]={["hands_feet"]="FFFFFF",["eye_white"]="D4CDC2",["nails"]="0B7F7F",["ear_tips"]="FFFFFF",["base"]="33AA3A",["eye"]="00AAAA",["inner_ear"]="BFBFBF",["nose"]="000555",["head_highlight"]="9D9FBF"},["sz"]="1.2",["h"]=0,["g"]="f",["r"]="x"}~~

The Wailer token gear

ID: 10008
~~Kyshf hide Helmet:  c2:{["a"]=[{["type"]="Armor-Heavy-High1-Helmet",["node"]="helmet",["colors"]=["3F352C","7AA3E9","D4B0D4"]}],["c"]={["collar"]={["type"]="Armor-Medium-Mid3",["colors"]=[]}},["b"]="n",["sk"]={["hands_feet"]="FFFFFF",["eye_white"]="D4CDC2",["nails"]="0B7F7F",["ear_tips"]="FFFFFF",["base"]="33AA3A",["eye"]="00AAAA",["inner_ear"]="BFBFBF",["nose"]="000555",["head_highlight"]="9D9FBF"},["sz"]="1.2",["h"]=0,["g"]="f",["r"]="x"}~~

ID: 10009
~~Deathchanter bow: c2:{["a"]=[{["type"]="Item-Bow-Medium3",["node"]="left_hand",["colors"]=["151515","E9E9E9","BF3434"]}],["h"]=0,["b"]="n",["sk"]={["hands_feet"]="FFFFFF",["eye_white"]="D4CDC2",["nails"]="0B7F7F",["ear_tips"]="FFFFFF",["base"]="33AA3A",["eye"]="00AAAA",["inner_ear"]="BFBFBF",["nose"]="000555",["head_highlight"]="9D9FBF"},["r"]="x",["g"]="f",["sz"]="1.2"}~~

ID: 10010
~~Soulweaver Kilt : c2:{["h"]=0,["c"]={["leggings"]={["type"]="Armor-Medium-Epic3",["colors"]=["d4b293","bfbfbf","d4b293","3e307f","2a0223","ff00fd"]},["collar"]={["type"]="Armor-Medium-Mid3",["colors"]=[]}},["b"]="n",["sk"]={["hands_feet"]="FFFFFF",["eye_white"]="D4CDC2",["nails"]="0B7F7F",["ear_tips"]="FFFFFF",["base"]="33AA3A",["eye"]="00AAAA",["inner_ear"]="BFBFBF",["nose"]="000555",["head_highlight"]="9D9FBF"},["r"]="x",["g"]="f",["sz"]="1.2"}~~

The rest of the gear is in the IGF anything for Folkirk will be put in the essence chest it will have no token gear due to small dungeon (less mobs to drop tokens) Any Wailing Crypt Gear is token gear.

Now for the check list.

GRUNES TAL

-All quests need to be activated with map markers.

Em - Done ~~-Map has to be set~~

-All NPCs and mobs need to be doubled check for having designs and Scripts (most mob packages are mixs) so maybe use Greths Spreadsheet to go through and add Scripts.

Em - Done ~~-All instance entrances need to be activated (including the one inside Folkirk that leads to the main section of the dungeon) as well as the Friendly instance in the friendly warpid town grove is devgrove1 in my grove list.~~

-walls and rubble need to be removed to allow entrance to Grunes

Em - Done by Ric ~~-Path nodes need to be check and fixed in the overworld  ( some mobs walk up trees or mountains)~~

-dungeon/essence chests need locations.

Done ~~-Drop rates for dungeons need to be set ( Due to the difficulty of the 2 Grunes Dungeons i wanted their drop rates to be a fair bit higher) I was thinking 
 Green 1-20
Blue 1-40
Purple 1-75/100 (will need testing)
Legendary 1 - 1000
Boss' Gurantee 2 Epics at least 1- 10 for Legendary~~

**Comment by rockfireredmoon** [comment]
All done I believe
