### ISSUE TITLE
Delivery boxes unuseable

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#102]
Reported By: Sejenus Caine
Category: OTHER

Dragging an item onto one of the three boxes does not work.
The boxes have the "inactive" look to them and the dragged item does not "stick".

Is this because my account is one of the older  "Greth archive" ones?

**Comment by Heathendel** [comment]
It's because you have t bough any delivery box slots from the credit shop

**Comment by rockfireredmoon** [comment]
This might also be an attempt to drag items from **inventory**, not **vault**. Currently items must be in the vault before they can be in a delivery box.

If the player had bought no delivery boxes, the slots would not even appear.

**Comment by rockfireredmoon** [comment]
Closing, no more responses so assuming fixed.
