### ISSUE TITLE
Mislocated Grunes Mobs?

### ISSUE THREAD

**Issue by LiskaQuicksilver** [rockfireredmoon/iceee#103]
Okay, I haven't been on in nearly a week and forgot to post this back then, but, here goes: While exploring Grunes Tal the last time I was online, I had noticed that in a camp that was supposed to be one of the Culler camps, a bunch of Undead Chirurgeons had been spawned instead. Not sure if this was an intentional change or an accidental one, so reporting just in case.

**Comment by Heathendel** [comment]
hmm wonder if they somehow got mixed up in that spawn package?

**Comment by rockfireredmoon** [comment]
Does anyone have an exact location for these?

**Comment by LiskaQuicksilver** [comment]
Sorry bout that Em. Meant to do that yesterday. Here: "(54527.7,724.247,65838.3,9)"

**Comment by rockfireredmoon** [comment]
Thanks :) Fixed
