### ISSUE TITLE
Please add my missing quest redux to Rose Farwalker in Ironbirch Camp

### ISSUE THREAD

**Issue by LiskaQuicksilver** [rockfireredmoon/iceee#105]
Here's the deal. Back when Greth was still at the helm, among the Grunes Tal quests I created is a Redux version of Rose Farwalker's quest "The Hand - Travel to Grunes Tal". The original SPM version indicates that the road into Grunes Tal is still closed (via rockslide). This new version I half-wrote slightly retools the existing quest to indicate that the road to Grunes Tal is now open (rockslide has been cleared). The data can be found in the /igf with my other quests.

This should have been added on the dev server but was inexplicably omitted. As the original SPM quest is now out of date on both servers since Grunes Tal is now officially open to players on both, the existing quest needs updating to my Redux version.

**Comment by rockfireredmoon** [comment]
Fixed
