### ISSUE TITLE
EE Character Museum

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#107]
Reported By: Hiromi Swiftwind
Category: OTHER

Does it still exist? Did it fall  through the cracks?  /museum doesn't work.

**Comment by LiskaQuicksilver** [comment]
Alright, I tested this on both the dev server and the main server. The museum is still there fully intact and accessible. Might have just forgotten the /warpi command I suppose.

**Comment by rockfireredmoon** [comment]
Marking as invalid. Re-open if this turns up again.
