### ISSUE TITLE
Fall Damage

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#112]
Reported By: Cory Lopez
Category: OTHER

There's no Fall Damage in the game it seems :(

**Comment by Heathendel** [comment]
That I also known it's been deactivated for the time being we are unsure if
and when we'll deactivate it :)

**Comment by rockfireredmoon** [comment]
Well, I added the commented out code back and gave it a quick test. Seems to work, but the testing wasn't thorough at all. So I made this a configuration option, so it can be change easily without recompiling the server. I might enable it as an experiment on the next update :)

**Comment by rockfireredmoon** [comment]
Fall damage will not be enabled in this update
