### ISSUE TITLE
the Five Flames

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#132]
Reported By: Stanjr Iceberg
Category: QUEST

Doing a emote worship by the flame outside the temple, but no actions seem to be happening???  Help?|!

**Comment by LiskaQuicksilver** [comment]
This one is that notorious issue where you must type /Worship to get it to work. This isn't a bug, just the game being picky. (thanks alot SPM!)

**Comment by rockfireredmoon** [comment]
Fixed. emote based quest objectives will now test the emote name in a case insensitive way. Upshot is both 'Worship' and 'worship' will both work (or 'WoRsHiP' for that matter)
