### ISSUE TITLE
Infinite Bounder Dash

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#134]
Reported By: Liska Quicksilver
Category: CHAR

Here's how this goes: Apparently when Bounder Dash is about to expire, the buff counter glitches (the icon blinks as it does just before the buff expires) and you get something like this on the timer: 

Duration: 24855d 2h 43m 29s

The counter still decrements the time, but, as shown above, it's an insane amount of time suddenly.

**Comment by LiskaQuicksilver** [comment]
Here's a screenshot as an illustration of what exactly I'm seeing in the above bug report.
![infinite bounder dash bug](https://cloud.githubusercontent.com/assets/12076163/10713460/1bce0e0c-7a86-11e5-9773-ca8d91455792.png)

**Comment by rockfireredmoon** [comment]
Cannot reproduce. A couple of questions ..

* Did you logout / in while the buff was running? Were the times correct the relog
* Did the buff actually stop working after 10 minutes (i.e. did you speed return to normal). Server side, buffs are timed separately and I am hoping this is just a client time calculation problem.

**Comment by LiskaQuicksilver** [comment]
The Buff/Timer Bug has finally met it's end. Closing.
