### ISSUE TITLE
Updates to QuestAnglorum.txt in both TAW and TSoA

### ISSUE THREAD

**Issue by LiskaQuicksilver** [rockfireredmoon/iceee#149]
Essentially I have completely combed the entire QuestAnglorum.txt files on both the Anubian War and Scourge of Abidan branches of the server files and fixed, corrected and tweaked all quests that needed work.

Some quests either required a bit more attention than the others or had 'special reasons' for their fixes.

These quests include:
Bandit Connection? - For the longest time, the quest text for this quest was vague and obscure. Although it was easy for players to find their way through the objectives, the 'story' seemed to be missing important data causing a huge plothole. Late in Planet Forever, while cataloging things, I stumbled across the quest's missing data in the Journal where it has been for who knows how long. At long last, the quest text that was stuck in the Quest Journal has been moved to the main quest window and new text has been added to the initial act of this quest to fill the gap.

BOUNTY: Steppe-Slimer - This Bounty Bpard in Camelot has often been missed by players due to it's level range being that of the Fort Stonehenge Boards rather than the other Camelot Board making it easy to outlevel by the time players arrived in Camelot. I have readjusted it's quest levels so that it matches the other Camelot BB rather than the Fort Stonehenge set.

Basic Duty - This has been a thorn in my side for a long time as this quest should not have been made available until the player has completed the quest 'The Militia House' in Camelot. As the Militia House quest chain actually begins with the 'Speak with Sir Kay' quest given by King Arthur, this 'break' in the chain has needed fixing. I have added in the needed requirement for 'The Militia House' quest's completion before any of the Militia House content can be taken, thus relinking the above two quests to the rest of the chain. Seems extreme, yet, this is how it always should have been.

Assaulting the Keep - Another long time thorn in my side, this quest, historically, caused quite a bit of gender confusion with players regarding the kill target Konin Graves by referring to Konin as male when the model has always been female. I have resolved this long standing issue at long last by changing the quest text to refer to Konin as the female she always has been.

The Treasure Map - Perhaps the most infamous EE quest of them all, this quest was removed early in the SPM era as players often complained how hard it was due to extremely vague clues and no quest markers to guide them. Worse, the reward for finishing the quest was lackluster and not worth the trouble. This reward was moved to the previous quest, The Fate of Baron Unger, after The Treasure Map's untimely removal from the game. In the hopes of one day seeing it restored, I have taken the liberty of adding in 'story' hints to the quest in the hopes it helps guide players where they need to go without the need for markers so that the quest's challenge is mostly preserved. Now all this quest needs is more appropriate rewards for the trouble...

The Gloom Witches - The long-running Red/Blue gag with this quest and associated dungeon has been long established among EE veterans. This quest would indicate the questgiver's 'soul' piece was sealed in a 'Red Bottle', yet when players would run the dungeon, the Bottle in question was actually Blue. As the prop and questline were never brought in line, players just got used to the idea and it became a running joke. I have finally put this joke to rest as at long last the Blue Bottle within Coldstorm Cavern is now referred to in the quest by its correct color: Blue.

Trouble in Nottingham - This quest has actually had very few problems, yet a bit of a story plothole has existed within the quest text itself. When the player would accept this quest, they would be directed to go meet Robin Hood as per the quest's objective. Oddly, the questgiver, Master Sergeant Illius, never even mentions Robin Hood in the quest text much less asks them to meet him at all! After spotting this story plothole, I extended the quest text to fill in this previously missing information.

**Comment by rockfireredmoon** [comment]
Confirmed fixed
