### ISSUE TITLE
Accidental Grunes Tal and Swineland rollback on Main Server

### ISSUE THREAD

**Issue by LiskaQuicksilver** [rockfireredmoon/iceee#155]
Okay, so, both Heath and I have noticed or have been told by players that Grunes Tal has reverted to being unopened again. After rechecking it, the boulders have been removed and the region is again open; however, most of the Grunes content is still very much missing, including the environment.

This was likely caused by the scenery files from Greth's Harvest Fest 2013 set and when it was copied over for the Harvest Fest 2015 event, everything got reverted to the state of those regions during that time. The easy fix here is to isolate the scenery files belonging to both Grunes Tal and Swineland on the Main Server's regular setup and copy back over those files so the completed regions are restored to the live server again.

I should stress this would best be done BEFORE the end of the Harvest Fest event and prior to a backup of the event for next year. This should also be taken into account when setting up this year's Winter Dawning event as well so that we do not get a second reversion as well as getting both event files ready for next year's Harvest Fest and Winter Dawning events.

Edit: It seems many of the changes I made to the Credit Shop content was also reverted inexplicably.

**Comment by rockfireredmoon** [comment]
Fixed
