### ISSUE TITLE
Road to Hell

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#156]
Reported By: Vlad Bishop
Category: QUEST

Speak to Hell "Twelve" is missing, he is not at the top of the mountain.  Can you help?   I am currently at the location of the quest marker, and there is no one here.  Thank you for your help, have a great holiday! 

Cheers mates

Vlad

**Comment by LiskaQuicksilver** [comment]
I have confirmed both the NPCs "Hell" Twelve and Mike Zean are among the 'damages' regarding the Holiday event content botch. These should be restored once this related issue has been resolved.

**Comment by LiskaQuicksilver** [comment]
This has been resolved. Closing.
