### ISSUE TITLE
Restoring Demoted Mobs to Old Rankings

### ISSUE THREAD

**Issue by LiskaQuicksilver** [rockfireredmoon/iceee#16]
The idea here is to essentially go through the spawn list for the existing regions of Anglorum and Europe and identify the Bosses and Quest targets that were demoted in rank during the Sparkplay era and restore them to their original ranks as seen during the early versions of the game.

The list so far is as follows:

Priestess Claira (currently Normal rank, originally Heroic rank) in Underhenge in Anglorum (done)
Magmange (currently Normal rank, originally Heroic rank) in the Coastal Cave in Midlands (done)
Darkhoof (currently Heroic rank, originally Epic rank) in the Midlands overworld (done)
Dreadclaw (currently Normal rank, originally Heroic rank) in the Sea Cave in New Badari (done)

Will add more to the list as others are noted.

**Comment by Heathendel** [comment]
Also Kilvath and whatever that elementals name is need to be returned to Legendaries

**Comment by rockfireredmoon** [comment]
Closed. Please open another issue if more are found
