### ISSUE TITLE
Battle Mage chestpiece missing from Credit Shop

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#188]
Reported By: Heroic Bunny
Category: ECON

Sorry to be "that guy", but as the title says, the Battle Mage chestpiece is missing from the Credit Shop.

**Comment by LiskaQuicksilver** [comment]
Just going to say this item is also missing from the dev server's Credit Shop, so both servers need this fixed.

**Comment by rockfireredmoon** [comment]
Fixed
