### ISSUE TITLE
Entering Zhushi Lair

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#196]
Reported By: Stanjr Iceberg
Category: QUEST

Have the quest, but have been unable to enter for some time. Hitting the point where you can enter is either very same or not set very well.. HELP!!!

**Comment by Heathendel** [comment]
that instance entrance is a bit wonky try jumping up a bit closer before
clicking it should work but ill attempt to adjust the prop

**Comment by Rictar-Gasper** [comment]
fixed on Main server need to fix on dev

**Comment by Rictar-Gasper** [comment]
copied and pasted what the fix from the main server to the dev

fixed closing issue
