### ISSUE TITLE
Grunes Tal Dead Space Repop (Done)

### ISSUE THREAD

**Issue by Rictar-Gasper** [rockfireredmoon/iceee#20]
Rictar is starting from the Warpig town and starting downwards 
Notes: added 2 new warpig towers to 62987,57533 and 2 new guards added a guard that walks from the town to the 2 towers ( why would they not gaurd the higher ground)

**Comment by Rictar-Gasper** [comment]
![gtmapdone](https://cloud.githubusercontent.com/assets/12091905/7383968/4e56ae12-edd5-11e4-9dcd-a85466e8df7d.PNG)

Progress Sofar

**Comment by rockfireredmoon** [comment]
Nice job Ric :)
