### ISSUE TITLE
Grunes Tal quest completion

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#21]
Use this task to note down quests you are currently working on. First check here to see if somebody else has already started or completed one, if not, make a new comment that you are now working on a quest. Edit the comment to say its completed when you are done.

For now we are assigning a small range of Quest ID's to each developer. Please use numbers from the range in the 'ID=' entry of each quest.

Em: 808-817
Heath: 818-830
Liska: 831-843

**Comment by Heathendel** [comment]
The Shadowfield Completed ID=818
General Bodiccea Completed ID=819

**Comment by rockfireredmoon** [comment]
Done
