### ISSUE TITLE
Mohawk Alert!

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#216]
Reported By: Hiromi Swiftwind
Category: CHAR

I logged in this morning, and my PURPLE MOHAWK is gone!  OMGWTFBBQ!  Please help!

**Comment by rockfireredmoon** [comment]
I am not sure what has happened here. I can see the item is definitely not in Hiromis inventory, but it still exists. I will send one to her via delivery box. If she had crafted stats on to it, and I am sure she did, then maybe we can make up for it in some other way.

Leaving open for now.

**Comment by rockfireredmoon** [comment]
Oh damn. It's bound, so cannot use delivery box. Will have to give it back to her in game.

**Comment by Rictar-Gasper** [comment]
i gave her one
