### ISSUE TITLE
The five flames

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#223]
Reported By: Temrin Sanjem
Category: QUEST

"worship at the flame near the temple" I have used the emote around it and on it and it will not complete the objective.

**Comment by LiskaQuicksilver** [comment]
Okay, Em, Rictar and I have tested this quest through every objective. ALL the Flames respond to odd things but not Worship or worship (though rarely does). I don't know what you did when you modified the quest, but, you might want to check your code to see what got mucked up.

**Comment by rockfireredmoon** [comment]
Fixed
