### ISSUE TITLE
Iron Maw Bosses

### ISSUE THREAD

**Issue by Heathendel** [rockfireredmoon/iceee#23]
Hey I had a bit of time to make Aneixma and 4 Sub Boss' for the Iron Maw they just need scripts and mechanics but if you get a chance add them in :) so i can place them :)

[ENTRY]
ID=3687
level=50
display_name=Anexima
sub_name=The Dragon Lich
creature_category=Unliving
rarity=3
appearance=c2:{["a"]=[{["type"]="Item-1hAxe-Med2",["node"]="left_hand",["colors"]=["295520","946624","944D0D","0E1508"]},{["type"]="Item-1hMace-Basic5",["node"]="right_hand"}],["c"]={["boots"]={["type"]="Armor-Light-Low1",["colors"]=[]},["chest"]={["type"]="Armor-Light-Low1",["colors"]=[]},["arms"]={["type"]="Armor-Light-Low1",["colors"]=[]},["leggings"]={["type"]="Armor-Light-Low1",["colors"]=[]},["collar"]={["type"]="Armor-Light-Low1",["colors"]=[]},["belt"]={["type"]="Armor-Light-Low1",["colors"]=[]},["gloves"]={["type"]="Armor-Light-Low1",["colors"]=[]}},["b"]="n",["sk"]={["hair"]="843C2B",["leg_patches"]="843C2B",["chest_patch"]="974632",["tusks"]="BFBE5E",["eye_white"]="ADADAD",["nails"]="63594E",["base"]="90AA5E",["inner_ear"]="994936",["eye"]="B18B65",["eye_brows"]="B25540",["snout"]="6F6152",["arm_patches"]="6E3325"},["sz"]="1.0216",["h"]=0,["g"]="m",["r"]="k"}
strength=425
dexterity=400
constitution=550
psyche=425
spirit=400
base_damage_melee=325
damage_resist_melee=6500
damage_resist_fire=6500
damage_resist_frost6500
damage_resist_mystic=6500
damage_resist_death=6500
profession=2
ai_package=custom_heathendel_anexima

[ENTRY]
ID=3688
level=50
display_name=Drakkar Zol
sub_name=The Relentless 
creature_category=Unliving
rarity=2
appearance=n4:{["sk"]={["bone"]="705C41",["trim"]="7F0B0B",["straps"]="B96464",["horns"]="463749",["armortrim"]="AAA937",["robe"]="000000",["armor"]="3F0000"},["c"]="Horde-Lich",["sz"]="1.0824"}
strength=350
dexterity=350
constitution=450
psyche=350
spirit=350
base_damage_melee=275
damage_resist_melee=6000
damage_resist_fire=6000
damage_resist_frost6000
damage_resist_mystic=6000
damage_resist_death=6000
profession=2
ai_package=example

[ENTRY]
ID=3689
level=50
display_name=Valkalth
sub_name=The Merciless
creature_category=Unliving
rarity=2
appearance=n4:{["sk"]={["bone"]="000000",["trim"]="7F7F7F",["straps"]="BFBFBF",["horns"]="000000",["armortrim"]="000000",["robe"]="000000",["armor"]="00033F"},["c"]="Horde-Lich",["sz"]="1.0824"}
strength=350
dexterity=350
constitution=450
psyche=350
spirit=350
base_damage_melee=275
damage_resist_melee=6000
damage_resist_fire=6000
damage_resist_frost6000
damage_resist_mystic=6000
damage_resist_death=6000
profession=2
ai_package=example

[ENTRY]
ID=3690
level=50
display_name=Karayan Vexx
sub_name=The Unholy
creature_category=Unliving
rarity=2
appearance=n4:{["a"]=[{["type"]="Item-Staff-Epic5",["colors"]=["2A0000","2A2A23","7F1100","3F3F35","FF00FD"],["effect"]="Par-WE-Staff-Death",["node"]="right_hand"}],["c"]="Horde-Lich",["sk"]={["bone"]="705C41",["trim"]="000000",["straps"]="B96464",["horns"]="3F0000",["armortrim"]="006A06",["robe"]="7F7E00",["armor"]="3F2105"},["sz"]="2"}
strength=350
dexterity=350
constitution=450
psyche=350
spirit=350
base_damage_melee=275
damage_resist_melee=6000
damage_resist_fire=6000
damage_resist_frost6000
damage_resist_mystic=6000
damage_resist_death=6000
profession=2
ai_package=example

[ENTRY]
ID=3691
level=50
display_name=Braakurk
sub_name=The Devourer
creature_category=Unliving
rarity=2
appearance=n4:{["sk"]={["main"]="2C3B55",["highlights"]="BF0000",["cloth2"]="5C5C4C",["clawskin"]="AA8B8B",["cloth1"]="6E2618",["eye"]="551B54",["nails"]="FFFFFF",["rot"]="7F7F7F"},["c"]="Horde-Behemoth",["sz"]="2"}
strength=400
dexterity=300
constitution=650
psyche=200
spirit=200
base_damage_melee=350
damage_resist_melee=6000
damage_resist_fire=6000
damage_resist_frost6000
damage_resist_mystic=6000
damage_resist_death=6000
profession=2
ai_package=example

**Comment by rockfireredmoon** [comment]
Done, but ID's assigned are 

Anexima=7798
Drakkar Zol=7799
Valkalth=7800
Karayan Vexx=7801
Braakurk=7802
