### ISSUE TITLE
Alimat quest bug

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#233]
Reported By: Bandicoon Machete
Category: QUEST

Alimat seems to be already spawned once you enter his chamber, and after killing him and doing the channeling bit, he refuses to repop? Any ideas?

**Comment by Heathendel** [comment]
Theres been an odd script bug with the alimat for the last several months,
 where he wasnt spawning at all after channeling.  until its fixed weve
prespawned him to complete the quest

**Comment by rockfireredmoon** [comment]
Fixed
