### ISSUE TITLE
Final Touches for Grunes Tal

### ISSUE THREAD

**Issue by Heathendel** [rockfireredmoon/iceee#26]
So with the Quests being finished were done to the final touches before Grunes Tal can be released here's is the list:

- The follow quests need rewards added to them ( add others if i leave any out) 
~~General Bodiccea~~
~~The Revenant~~
~~Bahmut the Red Nose Wrath Stag~~
~~one of Moris Banners quests. ~~
~~Reward should be the same named item but with 4 options catering to all one class each Rare with similar stats to SPM rares of the same level (but try to make them still Ex SPM rare 12spi 20con, Grunes reward 20 spi 12 con or 15spi 15 con etc)~~

~~The Wailing Crypt essence needs fixin, The chest needs to be converted to a proper essence chest displaying the rewards.  The Wailer needs an essence item and drop 3 upon death (one for each player that the dungeon recommends)~~

~~The Wailign Crypt token chest needs to be created and added.  Tokens need to be made and added to the dungeon mobs drop list~~

~~Folkirk Essence chest.  Same as The Wailing Crypt sept for folkirk :)~~

~~Early Release packages need to be made: Deciding the definite contents of the packs and make them.~~

~~Dungeons both the Wailing Crypt and Folkirk Manor need their drop rates raised.  They will need to be a fair bit higher then regular dungeons i was thinking.~~

Done under other issue, need to discuss these. They are wildly different from other dungeons ~~Uncommon: 1-10~~
~~Rare: 1-20~~
~~Epic: 1-50~~
~~Legendary:1-400~~

~~Boss rates, Mini bosses B: 1-1                                       P:1-10                                       L:1-75~~
~~Boss: P:1-1          L:1-25~~
~~I know im forgetting something hopefully it comes to me if anyone has anything else post it~~

**Comment by rockfireredmoon** [comment]
Need vendor at Redeemer camp, General Merchant. Redeemer Quatermaster

**Comment by rockfireredmoon** [comment]
Oh need to check dungeon sanctuaries work

**Comment by rockfireredmoon** [comment]
All done
