### ISSUE TITLE
Unable to continue storyline

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#273]
Reported By: Sai Starlight
Category: QUEST

Quests which are essential to progressing the storyline, such as Assaulting the Keep, should not require more than one player to complete - there are very few, if any, people online at any one time, who may not necessarily want to or be able to help, leading to people getting stuck at a certain point in the story, which can be very frustrating.

**Comment by LiskaQuicksilver** [comment]
While we understand the population is low and agree it is very frustrating to have to do quests that require more than one player when next to no one is online, this is something we cannot mitigate easily. Many players get on, see the server is empty or their friends have not logged in or there is no one of their level online...and simply log off again. They do not wait long enough for others to get on either. This is something we WANT to mitigate but are currently having difficulty with.

That said, if a quest states 2 or more players to complete, then that is what is needed for that quest. Granted many of these can be soloed with the right build on the right class, but, this isn't always the case. It does suck when no one is on to help, but, the best thing that can be done is to patiently wait for someone to come online be it another player or a dev. We do understand the frustration ourselves and do what we can to assist players as we are able, but, even we cannot be online all of the time.

**Comment by rockfireredmoon** [comment]
Not really a bug. We will be revisiting single player options in TAW.
