### ISSUE TITLE
The dreaded party loot bug

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#276]
This really needs fixing as it is the only known cause for server crashes now.

**Comment by rockfireredmoon** [comment]
Have changed LootTag storage in Party to use automatic storage duration.

**Comment by rockfireredmoon** [comment]
If the party member (leader) leaves the server that all looting is 'held up' until they return.

**Comment by rockfireredmoon** [comment]
Fixed

**Comment by LiskaQuicksilver** [comment]
Have tested this one enough for now and it seems to be ready. Closing issue for now.
