### ISSUE TITLE
Rics Quest Bug Report

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#28]
~~Behemoth Assembly lvl 43~~
 
~~Still in the return text says "Return to Moris Banner (hand over the body parts)"~~

~~Ale-Battered Gloom Spites lvl 43 Unable to Finish quest will not let me turn in, it says on the quest tracker window "Return to MJ Price 0)"~~

~~Haunted Hill lvl 44~~

~~May be to hard for 1 person all heroic mobs~~

~~Under mini-map Quest Tracker says on killing all the mobs "Return to Shayne Twichtail(Return to Shayne Twitchtail)"~~

~~Misguided Intentions lvl 44

~~maybe to hard for one person all heroic mobs~~

~~The Wailing Crypt lvl 44 (first quest)~~
~~says 2 person quest can easily be done with 1 no heroics or killing of the named~~

~~Foresight of the Elders lvl 46 / The True Form of Nobility lvl 46~~

~~Not sure if this is a bug but it these quests were accessible at 45~~

~~The True Form of Nobility lvl 46~~

~~Under mini-map Quest Tracker says "Return to Quintus Lunarsong (The Folkirks are dead!)" when you kill the Folkirks~~

~~Instances~~

~~Wailing Crypt~~

~~Token chest needs work only a few items in there~~

~~Forklit Manor~~

~~No Tokens Chest or Tokens dropping, Rewards chest need to be reworked only 2 rewards there~~

**Comment by Rictar-Gasper** [comment]
The Wailing Crypt lvl 44 (first quest)
Level was set as 1 along with party Size

Beasts of Grunes Tal...   parts 1 and 2 
remove the periods they look out of place

Ale-Battered Gloom Spites lvl 43
quest tracker window still says "Return to MJ Price 0)" quest is working fine

Note unused chest in redeemer compound church across From Hans Longstrider it is a mob was probably meant for a quest chain end reward chest

A Gift With a Prices lvl 44
Should it be a A Gift With a Price?

Juntaland

NOTE: Vendors are empty
Just Havin' A Laugh
Second objective says "Deliver Boss Hogs TV (Deliver Boss Hawgs TV to Hogcatchers)"
No place to deliver the TV to can't finish quest

Felled Mushrooms 
Odd Quest Crown on minimap for Felled Mushrooms at 64442 56807 no NPC 
had to add quest Manually 
Upon finish it is says return to Rheskor but he is not active to let me turn in 
quest needs to be reunited with him

Possible Bug?
Entering the protectorate compound instance says boss hawg's above the minimap



Zahn Meris creature CID 7785 Protectorate Compound acting like a chest,I am unable to undertake her Quest "The Missing Envoy" naturally had to use /gm to add it manually

Hot Bug Wings lvl 44 
second paragraph says starts with "Git-outta/ -here" the "/" need to be removed

A Hot Bowl of Soup
~~Missing Mushrooms
never mind i just added spawners and it works now

**Comment by LiskaQuicksilver** [comment]
Ric, that 'unused' chest across from Hans is supposed to be Shar Zaris' NPC Chest to be accessed after the player completes the Iron Maw dungeon quest around level 50. The player is supposed to get a Key from him to obtain an item from it.

**Comment by rockfireredmoon** [comment]
All fixed
