### ISSUE TITLE
Unequippable, class-unidentified item.

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#280]
Reported By: Giallo Smol
Category: ECON

Picked up an item off of a named mob. The item is: Old Nehtu Sandals. Level 7, binds to character on pickup. Feet slot, Armor 0, +2 Psyche. Sells for 1 silver, 23 copper. The item appears to be missing a class designation, which makes it unequippable.

**Comment by LiskaQuicksilver** [comment]
I've tested this item as well to verify the bug. it indeed does not equip on a character and claims the player is the wrong class no matter what their class is. It makes me wonder how many other 'old' equipment items have this issue or if this item is the only one.

**Comment by rockfireredmoon** [comment]
Fixed
