### ISSUE TITLE
Sanctuaries

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#297]
Activate all Sanctuaries

**Comment by rockfireredmoon** [comment]
* Blood Keep  - DONE
  * Skrill Lair
  * Junk Palace
  * Nook Town
  * Mausoleum
  *  Front Line Camp
  *  Wartown - DONE
  * Redeemer's Camp might have one
  
 Also ..
 
 * Swineland Henge that needs activiating....
 * Grunes Tal Key Sanc....
 * The ability table needs altering so you can add in the Tier 6 Swineland Henge port skill.
 * credit shop portal spells

**Comment by rockfireredmoon** [comment]
Discovered mausoleum needs entrance / exit. All done, except for the actual location of the entrance from the overworld. @LiskaQuicksilver do you know where this is?

**Comment by LiskaQuicksilver** [comment]
Crossed off the Front Line Camp and Redeemer's Camp sanctuaries. Also crossed off the Mausoleum overworld entrance.
