### ISSUE TITLE
The Bloodkeep Drop Rates

### ISSUE THREAD

**Issue by Heathendel** [rockfireredmoon/iceee#300]
The following drop rates need to be applied to valkals BK.  
All the named mobs but have a 100% to drop an epic.  0% chance on green/blue 5% chance on Legendary
all 4 Vaj need 100% epic drop ( high chance of multiple epic drops) 0 chance of green/blue and 15% chance on Legendary.
Valkal needs an extremely high drop rate.  In addition to 3 essence, he needs to drop a handful of items in the range of 3-6 ( epic or higher) 50% legendary drop rate.

**Comment by rockfireredmoon** [comment]
Completed. This involved a new 'Drop Rate Profile' that may be attached to either an instance (this already existed) or now a creature def. I took the time to tidy up the code a bit. 

Needs testing properly with multiple players.
