### ISSUE TITLE
Make The Down Below instance lore friendly

### ISSUE THREAD

**Issue by LiskaQuicksilver** [rockfireredmoon/iceee#301]
This is actually simpler than it sounds, but, needs a bit of background to explain things better. Apologies for the wall of text that follows as I feel the need to explain the reasons for this 'simple' requested change. Further, these changes need not be made for the Valkal's Shadow expansion if it is deemed unnecessary; however, I would like for it to happen in The Anubian War whether or not VS is also altered.

The Down Below dungeon has always been an oddity in Earth Eternal as it has never conformed to the rest of the game, being intended as a playground for high level players to run around in. Historically, this dungeon lags so bad that few would bother running it. Thus, few realize that three of the enemies in this massive instance actually put the dungeon at odds with the very backstory of the game itself.

The 'story' quests behind this dungeon claim it is an ancient structure from the time of the Bleakness that was uncovered in a landslide, attracting members of the Adventurer's Guild to investigate it and further excavate it. Inside, players encounter the 'spirit' of Arianna Glennell, the Duchess who lived in the massive estate. As players go through the story of this NPC's quest chain, they end up traversing maybe two thirds of the entire dungeon total. Unfortunately, none of the quests for this dungeon ever send the player to the 'South Wing' section. This section comes in two parts and features mobs most players will never see unless they are trying to 'clear' the entire instance which is a feat unto itself and I can assure you VERY few players will bother.

Now to the purpose of this Issue. For whatever reasons, of the dozens upon dozens of mobs in The Down Below, a grand total of THREE bosses in this mostly unvisited area of the dungeon are of races that, if one follows the lore story, were not even on the Earth plane itself, much less part of the Beast Nations, when the 'events' supposedly happened in the dungeon's story setting. In fact, because the story explicitly states the dungeon is a relic of the Bleakness, that places the structure as dating to a specific time in the Age of Legend, Thus all the races that join the Beast Nations during the Age of Beasts cannot be included. That eliminates six player races right there. These are as follows:

The Clockwork: During the 'time' this dungeon's 'story' is supposed to take place, their creator Heraclitus is either on his island as yet alone, or has gone off to visit the Banta deep in Africa. It is entirely possible that he returned by this point, but, if he has already created the Clockwork, they are still very much his 'toys' during this period in time. So, that crosses off this race as eligible for inclusion in the dungeon.

The Grumkin: As this is the 'latest' race to join the Beast Nations, during the Bleakness in this earlier Age of Earth, their race would still be part of the People of the Skull, the mortal enemies of the Beast Nations. This, then eliminates this race as well.

The Sylvan: Alright, this race is admittedly murky as they 'mysteriously' don't exist in the lore outside their race lore. While I do plan to fix this at some point, the 'dryads' do not leave their trees until the Forestal War in the Age of Beasts. Thus, even if these 'tree spirits' existed since long before the Beasts themselves, they would still be bound to the trees throughout the Age of Legend including the Bleakness. Therefore, even with a currently shaky background, even this race must be excluded.

The Yeti: During this period in the lore, the Yeti are still high in the Alpine mountains trying to recover their numbers. While the Vampires 'may' have found reason to hunt them here and there during the Bleakness, they were 'mythical' to the ruined Beast Nations of the time. This, then, crosses off yet another race from the list.

The Cyclops: This race, according to their own race lore claims they are 'low-born' members of the Faerie. Thus, during the time of the Bleakness in the Age of Legend, they are still with the rest of the Faerie in their Otherworld home. Being on an entirely different plane from Earth at the time, this race is automatically disqualified from the dungeon (even though currently two of the three affected mobs use the Cyclops male and female race models).

The Daemon: Prior to their 'escape' from the Hell plane during the Age of Beasts, this race spent three Ages of Earth being enslaved by the Demons of Hell under Demon King Dagon. Thus, this race, wasn't even on the Earth plane at the time of the Bleakness. Thus, they too, are disqualified (even though one currently existing mob uses the Daemon male model).

Lastly, we have a seventh race that must be eliminated. That is, of course, the Lisian race. While they do exist during the Age of Legend, during the Bleakness, this race is unknown to all the Beasts of Europe save the Atavians who are being aided by them. It isn't until after Atan's time that the Beast Nations are made known of this race's existence and role as a 'secret weapon' against the Vampires. This simple fact disqualifies even this race from the dungeon.

With these seven races eliminated from the pool, the next task is to pick from the remaining fifteen races, likely picking two of the least used races in the dungeon itself - two because one has to replace the two Cyclops mobs and a second to replace the Daemon mob.

The names of these creatures are as follows:
Zack Emberfrost (cyclops male)
Keyt <Overseer> (cyclops female)
Flammus <Overseer> (daemon male)

I do not see any need to completely replace these three mobs, save only to switch out their race models and nothing more. Names, equipment and coloring can probably remain the same. The colors may need changing if the races replacing them require other color patterns, though. Beyond that, just a simple 'race model swap' is all that is really needed. If it is preferred that the original creatures are to be preserved, a duplicate mob can be made of them with a different creature ID that has the new race models and these new ones placed in the dungeon instead of the originals.

**Comment by rockfireredmoon** [comment]
![image](https://user-images.githubusercontent.com/7688839/49225077-04e05c00-f3db-11e8-8fd7-628b90ebc014.png)

I was too lazy to try and work out what races were the least used, so went with what looked right to me.

Zack and Key are now Longtail and Flammus is Atavian.

**Comment by LiskaQuicksilver** [comment]
These look good. Closing.
