### ISSUE TITLE
Nooktown quest

### ISSUE THREAD

**Issue by Heathendel** [rockfireredmoon/iceee#305]
Nooktown has multiple quests that need adjusting.
in need of a make over: upon completion you cannot accept your mystery reward 
Nooklre path. Borris Plans are not interactable ID 3531 for the creature
The Blasphamer: Quest should be fine just needs map marker changes to the Nook lre path I would have done it my self WE was not allowing me to pick an intances to add locations :/ 
Bug-Juice: should be fixed now, spawn package had incorrect IDs in there. was altered by Heath but worth double checking

**Comment by rockfireredmoon** [comment]
Fixed
