### ISSUE TITLE
Swineland Shop keepers

### ISSUE THREAD

**Issue by Heathendel** [rockfireredmoon/iceee#309]
The Shops for the shop keepers need to be made, and they need to be added to the system currently all vendor NPC have dungeon loot interfaces when interact with.

In addition the 3 Swineland Dungeons need their loot chests fixed.
Valkal Essence chest is currently boss hawgs
Boss Hawgs is currently King Wilhelm's as well as boss hawg only drops 1 essence needs to drop 2
Skrill queen dungeon loot needs to be added to the chest currently blank

**Comment by rockfireredmoon** [comment]
Fixed
