### ISSUE TITLE
Swineland Quests

### ISSUE THREAD

**Issue by Heathendel** [rockfireredmoon/iceee#313]
Hey Em not sure what you got done last night with the crashes that ended up happening but here is everything i noticed that still needs doing and what i noticed was done

Shop keeps done :)

Nooktown quests.  Didnt get a chance to retest The Nook le re Path quests but Bug-Juice still cant be turned in to Dixon.  And "Spreading the world of Nook still stops at not being able to turn the quest into Clint ( who doesnt even show the complete quest crown so could and ID not be tagged as Ender and giver.

Havent tested Skrill quests for that reason however the skrill have is still messed up as lots of movement missing from spawns, and the Hiveguards are absent again from their package should be lvl 48 hiveguard.

The only other issue in that chain besides the github issue and the one i just outlined would be the Duke bros quest in Clints chain ( very simple quest its literally a talk to and return quest, however with all the giver/ender trouble weve had wouldnt surprise me

The Redeemer camp.  The Redeemer camp is now 100% intact working for the first journey to the camp.  The return after defeating the Skrill Queen starting from "Break through with the Bloodkeep"
down to "The Cost of Peace" likely have more issues but heres what i noticed

Breakthrough with the blood keep should be good assuming Clint is fixed as a giver and ender
Piece of the puzzle ( simple kill quest however one vampire NPC has the wrong appearance the named mob.  Will see if i still have it saved and applied it to WE when its up and running.  Aside from that quest should be good.

The End is Near ( is just a report to the redeemer captain quest) currently Alain Darkfeather was the ender for this quest when it should be Orso Ironhide however i changed that in WE yesterday.  the quest should be repaired provided nothing got mixed up in WE for the sake of it maybe we should double check.

The Cost of peace is now in the system but is a blank quest no targets, not test no markers nothing... Not sure what wrong there but the proper entry needs to be added to WE with Orso Ironhide being the giver and ender

Tearing Down a Bloodline: this quest now appears to be absent from the game as well Just needs adding.

Hunting Legends seems to be fine worth double checking it can be given and ended but it seem to have been yesterday ( aside from giving as the required quest was missing). 

As of now thats all the quests in Swineland these corrections SHOULD been the region is good provided we get no more mix ups XD also going to copy paste this into a github issue

**Comment by rockfireredmoon** [comment]
All fixed, subject to testing
