### ISSUE TITLE
Missing Spawn appearances

### ISSUE THREAD

**Issue by Heathendel** [rockfireredmoon/iceee#314]
Kilvath is missing his appearance.  Not sure if this is from the same bug as the shop keep from nottingham but we need to assign a team member to go from town to town quest hub to quest hub as well as dungeon to dungeon checking mobs to make sure no others are missing and if so too correct them.

This issue should be updated when you have finished an area post that it has been checked.  This includes the starting zones.   If you are handy with World Edit you and creaturetweak feel free to make the appearance yourself if not simply post the NPCs/ mobs which require appearances and someone can address it :D

**Comment by LiskaQuicksilver** [comment]
I can confirm that ALL FOUR of the World Bosses have lost their appearances and not just Kilvath. Ni'Lania, Thara and L'ough have as well. (L'ough for the second time unfortuantely)

**Comment by Heathendel** [comment]
World Bosses have appearances now and Soulstrikers do too
