### ISSUE TITLE
More Swineland quest issues.

### ISSUE THREAD

**Issue by LiskaQuicksilver** [rockfireredmoon/iceee#324]
Okay okay, I know we're still having lots of issues with getting the new Swineland quest chains to function properly but, going to mention or reiterate this one anyway.

Was finally able to test more quests and discovered that the quest Puttin' A Quiver In His Liver is ONLY counting kills to the Haz'ard Scout mobs and none of the others. The Bashers, Skewers and Spellslingers are not being counted toward the quest.

**Comment by rockfireredmoon** [comment]
Fixed
