### ISSUE TITLE
The Junk Palace

### ISSUE THREAD

**Issue by LiskaQuicksilver** [rockfireredmoon/iceee#325]
Simply put, the quest objective still wants the player to 'kill' 15 non-existent 'bodyguards' of Boss Hawg even though the quest journal only mentions Boss Hawg and there are no 'adds' in the boss fight. This additional quest objective was supposed to be removed but somehow it was only removed in the Journal and nowhere else.

**Comment by rockfireredmoon** [comment]
Fixed
