### ISSUE TITLE
You Feelin' (Un)Lucky?

### ISSUE THREAD

**Issue by LiskaQuicksilver** [rockfireredmoon/iceee#326]
Not sure if this issue was added previously or not but Clint's quest 'You Feelin' Lucky?' does not update it's objectives. The player enters the Skrill Queen's Lair as per the first Act objective, however the message 'Entering Skrill Queen Lair' pops up as expected (the message might be slightly incorrect though) but the quest objective does not progress to the next act in the quest.

**Comment by rockfireredmoon** [comment]
Fixed
