### ISSUE TITLE
The Greysun Bandits

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#336]
Reported By: Sabina Hellroar
Category: CHAR

As checked by Sage frsotheim, the quest doesn't credit to any of the bandits camps in  the great forest. It's the start of the chain to the first camp. Going to it gives no credit.

**Comment by LiskaQuicksilver** [comment]
I can verify this. I'm wondering if the 'destination coordinates' for each objective in the first quest is missing. It's funny. I was concerned with the kill targets of the later quests in the chain that I somehow overlooked having this quest tested. Well, it has been now and it's indeed broken.

**Comment by rockfireredmoon** [comment]
Fixed. Was using floating point locations for the objective data, this is incorrect (unlike map marers, FP is not supported in these locations).
