### ISSUE TITLE
Healing Breeze is Broken

### ISSUE THREAD

**Issue by LiskaQuicksilver** [rockfireredmoon/iceee#339]
Going to be blunt. Casting Healing Breeze while in combat crashes the server. Has been tested by player Sharlexia and confirmed. I wonder if this has anything to do with some of the changes made recently that used Healing Breeze as a template. Please investigate.

Edit: Seems to be happening with Resurrect and Vigor of Sargon as well. There may be others that haven't yet been made known. Again, please check whatever changes have been made to these skills and see if there's a correlation. It's starting to make the game unplayable for players.

**Comment by rockfireredmoon** [comment]
Was fixed under #5c976b6e3488de43cddb4167b92ea907e6b03d02 (Reagents)
