### ISSUE TITLE
bug: Recognition of /region command in chat via click

### ISSUE THREAD

**Issue by HulkCougarstein** [rockfireredmoon/iceee#34]
if a player clicks on (region) the command line displays (party)

**Comment by rockfireredmoon** [comment]
Not strictly a bug, as it has just always been this way, but yeh, this has always driven me crazy too :) I'll see if it can be fixed.

**Comment by rockfireredmoon** [comment]
I was wrong, was a bug. Caused by incorrect decompilation of break statements. Fixed
