### ISSUE TITLE
mobs frozen

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#343]
Reported By: Arnica Skyflower
Category: MOB

greysun bandits and wayward murflies near first camp in great forest are frozen and facing the same way.

**Comment by rockfireredmoon** [comment]
Fixed. Added wander radius to the spawn package for these Greysuns and Murkfly

**Comment by LiskaQuicksilver** [comment]
Checked up on this, Quite frankly I don't think all the Greysuns needed to be given a wander radius. The ones around the tents, crates and campfires should be fine standing still. All the rest can wander freely.

**Comment by rockfireredmoon** [comment]
Have added a 2nd package 4_ewd_greySunMix2_35_nowander 

This should be used for the spawns in the camp (and rotation manually set to various angles individually).

**Comment by LiskaQuicksilver** [comment]
Gave the ones who needed it a wander radius, left the ones who likely should stand still remain static.
