### ISSUE TITLE
Critical Crash

### ISSUE THREAD

**Issue by Heathendel** [rockfireredmoon/iceee#344]
Hey Em the server needs immediate attention there was a large crash about an hour ago and the Live server says its down and wont reboot but players are connecting to the legacy server ( as they are sorta the same) this was all well and good until lbl 10 mobs started dropping lvl 50 rares and legendary items... all those items have been destroyed and both servers have been taken offline 

Were not sure what the cause is Heath was in Blood Keep when it happened aside from that im not sure what else was going on :)

**Comment by LiskaQuicksilver** [comment]
I can verify the server has a serious problem. I tried restarting it several times and while the old Legacy VALD server comes online just fine, the live VS (formerly SOAD) server tries to come online but doesn't every time. We've shut both down for now until you can investigate. Seems to be pretty serious.

I'm wondering if it has something to do with either your recent crash fixes or perhaps the hostname changes you made right before rolling out VS to the live server. Whatever is causing this issue, it needs immediate attention.

**Comment by rockfireredmoon** [comment]
Fixed. Well ... the server page on TAW site has been fixed, and mitigation against the cause of the crash (vuln. probes) has been  made.
