### ISSUE TITLE
Spiteful Lantereyes

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#367]
Reported By: Sabina Hellroar
Category: OTHER

According to Liska Quicksilver the attack scripts are gone. They simply do not attack any player nearby. I did a quest for them an they did not attack me at all.

**Comment by LiskaQuicksilver** [comment]
This has been resolved. The issue involved an empty script resulting in all mobs using the script to do nothing. All the affected mobs are active again.
