### ISSUE TITLE
Armor Refashioning

### ISSUE THREAD

**Issue by Frothel** [rockfireredmoon/iceee#37]
I know this might not be a bug, but can you allow for weapons and shields to be refashioned also?  I would think people would like that =)

**Comment by LiskaQuicksilver** [comment]
Weapons have been refashionable for the majority of Planet Forever's
existence and is still quite usable in IceEE PF. Grethnefar made this
available using the /refashion command.

Using the first two slots in your inventory (make sure they don't have
something else filling those slots), place the weapon or armor you want the
stats from in the first slot and the one with the desired look in the
second slot (this one will be lost once the action has been completed).
After this is done typing /refashion or /refashion 1 will perform the
action and deduct the refashion cost just as if you were at an armor
refashioner.

Far as shield refashioning goes, I am not sure on that one; but, if it does
work, they might be treated as armor when refashioning.

**Comment by Heathendel** [comment]
Shields are treated as off hand weapon they are refashionable with the
/refashion command but not with an armor refashion we do have plans to
change this we want to phase out all /commands and create new interfaces so
they are more player friendly

**Comment by rockfireredmoon** [comment]
Fixed. Same rules as apply with /refashion now apply to refashioner.
