### ISSUE TITLE
Quest completion bug

### ISSUE THREAD

**Issue by Heathendel** [rockfireredmoon/iceee#370]
Z Zelin is having problems completely quests when he speaks to an NPC he gets this
![image](https://user-images.githubusercontent.com/11857916/33517473-d3450d76-d752-11e7-855c-41a1bf4098a0.png)
hopefully you can see that :)  When trying to test it with Astor i wasnt able to open up any quests chats with NPCs to obtain a quest... Not sure if this is somehow related to the Fix we did for quest objectives and altering the window itself ? anyways definitely needs a addressing if players cant complete quests

**Comment by rockfireredmoon** [comment]
Fixed. Was indeed related to the objectives increase.
