### ISSUE TITLE
Purchasing a New Character from the Credit Shop doesn't seem to give a new slot.

### ISSUE THREAD

**Issue by LiskaQuicksilver** [rockfireredmoon/iceee#375]
This was reported to me by player Winterbeast. Essentially, he purchased a fifth character slot with credits via the Credit Shop 'add a character slot' option. However, when he went to use the slot, it wasn't available to him as if he had not even purchased it. And yes, he told me the game DID take his credits for the purchase but otherwise did nothing.

This seems to be a serious issue. Please investigate when able.

**Comment by rockfireredmoon** [comment]
While I cannot reproduce this in ordinary circumstances (have successfully created up to max of 8 slots), I did find that upon the 8th slot, you can purchase the item and use it, but will not be giving a new slot. I have changed this so the ability will not run now if at maximum. I don't think this particular player had this problem though. Regardless, I have also credited the player with 500 credits as well.

**Comment by LiskaQuicksilver** [comment]
Well, players can now purchases new slots easily now. However, this issue still persists as for some reason players are unable to get a purchased Character Slot to function after buying Character Six. In other words, for some reason players are unable to buy a seventh or eighth character slot because the New Character Slot item stops functioning after the sixth slot is purchased.

**Comment by LiskaQuicksilver** [comment]
Upon further tests, this issue has been discovered to involve the systemic depletion of Will in successive character slot creations. This is an intentional limitation for all abilities. So, it has proven to be a non-issue. If it later proves to be problematic for all 'activate on click on purchase' items such as those in the Credit Shop, we might choose to revisit the issue for possible tweaking. For now, it shall be left as is as the main functionality works as intended.
