### ISSUE TITLE
Skill Timers Break when Warping

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#377]
Reported By: Bel Aldur
Category: CHAR

I'm  not sure what triggers it, if it's warp or bind or henge, but many times after moving around or entering instances, the buff timers break. For instance, a 1 hour skill like vigor of sauron of spirit of solomon will only last a few minutes or so. Hard to replicate 100% of the time, but happens regularly.

**Comment by Heathendel** [comment]
I can confirm this bug

**Comment by rockfireredmoon** [comment]
Possible duplicate of #411

**Comment by rockfireredmoon** [comment]
Being tracked now under #469
