### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Frothel** [rockfireredmoon/iceee#40]
This is the second time this game has crashed on me.  I was in the middle of fighting 3 mobs when it crashed, in Rapunzel's Tower, level 3.

**Comment by Frothel** [comment]
And once it crashes, I have to re-download the files for the Beta server before I can play again, as it is stuck in perpetual crash mode. (Once I double click the link, it says it has to close the program)

**Comment by rockfireredmoon** [comment]
Hi Frothel.

If this happens again, could you look in your installation directory for the file "Player.log" and post the contents here. You have to do this before starting the client again as it will wipe out the previous log.

**Comment by rockfireredmoon** [comment]
Out of date
