### ISSUE TITLE
Game hangs during second Valkal fight

### ISSUE THREAD

**Issue by LiskaQuicksilver** [rockfireredmoon/iceee#409]
Players Sharlexia, Horsey and Aureus brought this one to my attention yesterday and I tried to replicate it alone with no success. That said, I was able to convince them to run the entire Valkal boss fight again with me tagging along with Sage Frostheim as a party member.

Sure enough, during the second fight with Valkal, the game hung right after Valkal used Tribute on Aureus, killing him. In their previous runs, this seemed to happen only around the time they defeated Vaj Angelus (the Third Son or first add of the fight) and tried to re-engage Valkal while looting Angelus. Aureus theorized it was because Sharlexia, being the party healer, was technically 'not in combat' so it was messing up the boss fight scripts.

As it happened, I was also 'not in combat' during my run with them using Frostheim. Valkal had disengaged before I could re-enter combat after being pulled out of combat during the fight. I suspect the server is freaking out over existing player IDs not actually being 'available' even if the players themselves are online and/or are participating in the fight, but, cannot actually confirm the exact nature of this crash as it seems oddly erratic.

In spite of our rigorous testing of the Valkal boss fight stages, it seems this particular crash bug slipped under our radar. Also, because of this same issue, at least this particular party of players cannot complete the quest without crashing the server in the attempt.

**Comment by rockfireredmoon** [comment]
Fixed.

**Comment by LiskaQuicksilver** [comment]
This bug has proven to persist. Was able to duplicate the original crash instance during testing. Reopening this issue until it has been resolved.

**Comment by rockfireredmoon** [comment]
Fix attempted. Please retest.

**Comment by LiskaQuicksilver** [comment]
Again, this was due to an integer overflow and has now been resolved.
