### ISSUE TITLE
Grove Permissions not enabled for Player Accounts

### ISSUE THREAD

**Issue by LiskaQuicksilver** [rockfireredmoon/iceee#414]
This was brought to my attention earlier in the year and I tested this around the same time. My own character Liska was indeed unable to utilize the commands /togglebuilding and /creaturetweak in his own grove. (also outside it in the case of creature tweak, which is likely intended)

At first I presumed the permissions for these had been lost for all accounts but later tests on my Sage account revealed my Sages could still use both commands anywhere.

Have also had several players inform me they could not build in their groves, but, have since taken to informing players these commands are broken for the time being. A fix for these is badly needed as playing in Groves is a large part of the game, especially for those tired of grinding levels in the main overworld or in dungeons.

**Comment by rockfireredmoon** [comment]
Fixed. Will be available in next client build.

**Comment by rockfireredmoon** [comment]
Fixed. Please test ..

- That ordinary players can edit in grove
- The ordinary players CANT edit anywhere else
- Admins can edit anywhere

**Comment by rockfireredmoon** [comment]
Confirmed fixed.
