### ISSUE TITLE
Getting back in

### ISSUE THREAD

**Issue by Frothel** [rockfireredmoon/iceee#42]
I try to launch the application and it is not letting me back in.  It is stuck at awaiting download request on a black screen.

**Comment by Heathendel** [comment]
The server made have crashed or Emerald is updating it

**Comment by LiskaQuicksilver** [comment]
The server crashed last night after the event. Refer to Em's bug report on the Squirrel compiler for the possible cause. She has yet to bring the server back up, so is likely keeping it down until that issue is resolved. We won't know everything until Em gets the server online again.

**Comment by Frothel** [comment]
ahh ok ty

**Comment by rockfireredmoon** [comment]
Suspect script system bug which should be fix. Closing
