### ISSUE TITLE
Another loot related server crash

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#421]
16:08:42 Failed to activate ability 228 because error code 6 (6).^M
16:08:42 Failed to activate ability 228 because error code 6 (6).^M
16:08:42 Failed to activate ability 228 because error code 6 (6).^M
16:08:42 Failed to activate ability 228 because error code 6 (6).^M
16:08:42 Failed to activate ability 228 because error code 6 (6).^M
16:08:42 Failed to activate ability 228 because error code 6 (6).^M
16:08:42 Failed to activate ability 228 because error code 6 (6).^M
16:08:42 Failed to activate ability 228 because error code 6 (6).^M
16:08:42 Failed to activate ability 228 because error code 6 (6).^M
16:08:42 Failed to activate ability 228 because error code 6 (6).^M
16:09:04 Saving ability 5,27,109,38,2092917^M
^M
16:09:04 Saving ability 5,3,118,43,592398^M
^M
16:09:04 Saved character -400044856 [Crashbang Tyron]^M
16:09:04 Finished autosave on 1 characters.^M
16:09:11 Script [melee_creature_brave_6] has ended^M
16:09:11 Script [melee_creature_brave_6] has ended^M
16:09:12 Script [melee_creature_brave_6] has ended^M
16:09:12 Script [melee_creature_brave_6] has ended^M
16:09:12 Script [melee_creature_brave_6] has ended^M
16:09:12 Script [melee_creature_brave_6] has ended^M
16:09:12 Script [melee_creature_brave_6] has ended^M
16:09:12 Script [melee_creature_brave_6] has ended^M
16:09:23 [SOCKET] Unspecified error: 9^M
16:09:23 [SOCKET] Disconnecting Socket:11^M
16:09:23 [SOCKET] Unspecified error: 9^M
16:09:23 [SOCKET] Disconnecting Socket:11^M
16:09:23 Thread for Sim:187 shut down.^M
16:09:23 ProcessPendingDisconnects - Sim:187^M
16:09:23 [Sim:187] Disconnecting client^M
16:09:23 Saving ability 5,27,109,38,2073257^M
^M
16:09:23 Saving ability 5,3,118,43,572738^M
^M
16:09:23 Saved character -400044856 [Crashbang Tyron]^M
16:09:23 RemoveCreatureTags in creature -400044856, item -1^M
16:09:23 RemoveCreatureTags HUH!!!! NULL value in loot tags map for 4 in creature -400044856, item -1^M
16:09:23 RemoveCreatureTags in creature -400044856, item -1^M
16:09:23 RemoveCreatureTags in creature -40004485

**Comment by LiskaQuicksilver** [comment]
Resolved.
