### ISSUE TITLE
Return to Danube Azure

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#423]
Reported By: Lightning King
Category: QUEST

Where there should be character dialogue for The Collector after the amulet is collected, the objective is restated. "Return to Danube Azure at the Gypsy Camp," says Danube Azure.

**Comment by LiskaQuicksilver** [comment]
Investigating the World Editor, this quest appears intact on this end. That said, if the quest is indeed somehow messed up on the live server, it's quite possible that this can be restored by re-uploading the quest text from the World Editor. Should be a quick fix.

**Comment by LiskaQuicksilver** [comment]
This issue is fixed.
