### ISSUE TITLE
Valkal Randomly Just Stops and Cannot Be Targeted then Crashes the Server...Again

### ISSUE THREAD

**Issue by LiskaQuicksilver** [rockfireredmoon/iceee#426]
Here we go again guys. ANOTHER Valkal server crash bug. I believe we encountered this one previously but it didn't crash the server last time. This time, Sharlexia, Horsey and Aureus again faced Valkal. After a very difficult fight, (see next issue in list) they got to the Second Phase.

Unfortunately, when the second Valkal spawned, no one could target him. I went there with Frostheim to help just in case, but, before I could fully load as the instance was extremely laggy for some odd reason, the entire server completely crashed. Aureus has stated it claimed 'you cannot attack this target' when he attempted to fight the boss. No idea what is going on here.

**Comment by LiskaQuicksilver** [comment]
Okay. For the information I can recall regarding the circumstances surrounding the odd crash that happened at this point in time.... After Valkal part 2 'stopped' I offered to help and hopped on Frostheim as mentioned. I cannot say for certain if the lag began before or after Frostheim had logged in, but, I do recall getting killed by Kilvath on Avalon right after logging in. After activating godmode and dev revival, I ported to Horsey. When I got into the Blood Keep the lag was just awful. Everyone and everything was cogs and both the players and their pets were very slow in loading. I think one pet and two players actually loaded before the crash though.

Anyway, I tried moving around and this was not easy so I decided to check the state of the lag by opening up the FPS meter. I accidentally missed and hit F8 instead and opened the item appearance window by mistake. Closing that, I hit F9 to open the FPS window. It opened alright.....but, then the client totally weirded out, with random loadscreens, a brief flicker to the login screen, back to loading screens, then finally just landed on the login screen for good. Thought it was my client bugging out at first, but, Horsey and Sharlexia confirmed the server had indeed crashed.

Thinking I was responsible for the action since the server crashed immediately after I opened the FPS meter on my client....I took the heat for it. Still don't know the exact cause though.

**Comment by rockfireredmoon** [comment]
Fixed. Requires testing under the new procedures. @LiskaQuicksilver , am assigning to you. We'll start using the new rules now, soepending on the outcome of your testing, please either add the 'fixed' label and CLOSE the issue, or the 'failed-testing' label and leave it reopen and make sure it is assigned to me.

**Comment by LiskaQuicksilver** [comment]
This was due to an integer overflow issue and it has been resolved.
