### ISSUE TITLE
Valkal Boss Difficulty Has Greatly Increased?

### ISSUE THREAD

**Issue by LiskaQuicksilver** [rockfireredmoon/iceee#427]
Okay. This one left me puzzled a bit. According to Sharlexia, Horsey and Aureus, for some odd inexplicable reason, Valkal is MUCH MUCH more difficult to fight than previously. On Phase 1 alone, both Sharlexia and Aureus were both forced to spam Heals on Horsey while Horsey literally pumped themselves with level 50 healing potions just to stay alive during that entire half of the boss fight.

Not sure what is going on here, but, during our testing Valkal was nowhere that difficult. Horsey lost about 50 Gold on just potions alone thanks to the crash issue on the Phase 2 portion of the fight. (see previous issue)

Anyway, we might want to investigate this one and see if some setting got unknowingly tweaked or what happened.

**Comment by rockfireredmoon** [comment]
Fixed
