### ISSUE TITLE
Iron Maw Mobs 

### ISSUE THREAD

**Issue by Heathendel** [rockfireredmoon/iceee#44]
Hey Em finished up the Iron Maw mobs they dont have scripts yet i want to make scripts for the Raid dungeons (can obviously be done later) but all the stats and designs etc are made.  I also re added the Bosses from Iron Maw as i noticed a small typo in their frost armor value there was no = could do nothing but might as well fix it so the boss' im sending you here are fixed.

Could you also make a the Spawn packages for the dungeon. Have Subterranean Crawlers Stagnant Air, Life Ember and Krostakin Scout in one and All the other mobs (save for the boss') in the other and then the proper spawn packages for the boss' ex. WC_56_Wailer 

Once you get them added i can add all the spawns and pathnodes and loyalty to the mobs and all that will need doing is AIs and mechanics :)

[ENTRY]
ID=3687
level=50
display_name=Anexima
sub_name=The Dragon Lich
creature_category=Unliving
rarity=3
appearance=c2:{["a"]=[{["type"]="Item-1hAxe-Med2",["node"]="left_hand",["colors"]=["295520","946624","944D0D","0E1508"]},{["type"]="Item-1hMace-Basic5",["node"]="right_hand"}],["c"]={["boots"]={["type"]="Armor-Light-Low1",["colors"]=[]},["chest"]={["type"]="Armor-Light-Low1",["colors"]=[]},["arms"]={["type"]="Armor-Light-Low1",["colors"]=[]},["leggings"]={["type"]="Armor-Light-Low1",["colors"]=[]},["collar"]={["type"]="Armor-Light-Low1",["colors"]=[]},["belt"]={["type"]="Armor-Light-Low1",["colors"]=[]},["gloves"]={["type"]="Armor-Light-Low1",["colors"]=[]}},["b"]="n",["sk"]={["hair"]="843C2B",["leg_patches"]="843C2B",["chest_patch"]="974632",["tusks"]="BFBE5E",["eye_white"]="ADADAD",["nails"]="63594E",["base"]="90AA5E",["inner_ear"]="994936",["eye"]="B18B65",["eye_brows"]="B25540",["snout"]="6F6152",["arm_patches"]="6E3325"},["sz"]="1.0216",["h"]=0,["g"]="m",["r"]="k"}
strength=425
dexterity=400
constitution=550
psyche=425
spirit=400
base_damage_melee=325
damage_resist_melee=6500
damage_resist_fire=6500
damage_resist_frost=6500
damage_resist_mystic=6500
damage_resist_death=6500
profession=2
ai_package=custom_heathendel_anexima

[ENTRY]
ID=3688
level=50
display_name=Drakkar Zol
sub_name=The Relentless 
creature_category=Unliving
rarity=2
appearance=n4:{["sk"]={["bone"]="705C41",["trim"]="7F0B0B",["straps"]="B96464",["horns"]="463749",["armortrim"]="AAA937",["robe"]="000000",["armor"]="3F0000"},["c"]="Horde-Lich",["sz"]="1.0824"}
strength=350
dexterity=350
constitution=450
psyche=350
spirit=350
base_damage_melee=275
damage_resist_melee=6000
damage_resist_fire=6000
damage_resist_frost=6000
damage_resist_mystic=6000
damage_resist_death=6000
profession=2
ai_package=example

[ENTRY]
ID=3689
level=50
display_name=Valkalth
sub_name=The Merciless
creature_category=Unliving
rarity=2
appearance=n4:{["sk"]={["bone"]="000000",["trim"]="7F7F7F",["straps"]="BFBFBF",["horns"]="000000",["armortrim"]="000000",["robe"]="000000",["armor"]="00033F"},["c"]="Horde-Lich",["sz"]="1.0824"}
strength=350
dexterity=350
constitution=450
psyche=350
spirit=350
base_damage_melee=275
damage_resist_melee=6000
damage_resist_fire=6000
damage_resist_frost=6000
damage_resist_mystic=6000
damage_resist_death=6000
profession=2
ai_package=example

[ENTRY]
ID=3690
level=50
display_name=Karayan Vexx
sub_name=The Unholy
creature_category=Unliving
rarity=2
appearance=n4:{["a"]=[{["type"]="Item-Staff-Epic5",["colors"]=["2A0000","2A2A23","7F1100","3F3F35","FF00FD"],["effect"]="Par-WE-Staff-Death",["node"]="right_hand"}],["c"]="Horde-Lich",["sk"]={["bone"]="705C41",["trim"]="000000",["straps"]="B96464",["horns"]="3F0000",["armortrim"]="006A06",["robe"]="7F7E00",["armor"]="3F2105"},["sz"]="2"}
strength=350
dexterity=350
constitution=450
psyche=350
spirit=350
base_damage_melee=275
damage_resist_melee=6000
damage_resist_fire=6000
damage_resist_frost=6000
damage_resist_mystic=6000
damage_resist_death=6000
profession=2
ai_package=example

[ENTRY]
ID=3691
level=50
display_name=Braakurk
sub_name=The Devourer
creature_category=Unliving
rarity=2
appearance=n4:{["sk"]={["main"]="2C3B55",["highlights"]="BF0000",["cloth2"]="5C5C4C",["clawskin"]="AA8B8B",["cloth1"]="6E2618",["eye"]="551B54",["nails"]="FFFFFF",["rot"]="7F7F7F"},["c"]="Horde-Behemoth",["sz"]="2"}
strength=400
dexterity=300
constitution=650
psyche=200
spirit=200
base_damage_melee=350
damage_resist_melee=6000
damage_resist_fire=6000
damage_resist_frost=6000
damage_resist_mystic=6000
damage_resist_death=6000
profession=2
ai_package=example

[ENTRY]
ID=3692
level=49
display_name=Undead Miner
sub_name=Servant of Abidan
creature_category=Unliving
rarity=1
appearance=c2:{["a"]=[{["type"]="Item-1hAxe-MiningPick",["node"]="left_hand",["colors"]=["3F3F3F","6A3618"]}],["c"]={["boots"]={["type"]="Armor-Light-Low2",["colors"]=[]},["chest"]={["type"]="Armor-Light-Low2",["colors"]=[]},["arms"]={["type"]="Armor-Light-Low2",["colors"]=[]},["leggings"]={["type"]="Armor-Light-Low2",["colors"]=[]},["collar"]={["type"]="Armor-Light-Low2",["colors"]=[]},["belt"]={["type"]="Armor-Light-Low2",["colors"]=[]},["gloves"]={["type"]="Armor-Light-Low2",["colors"]=[]}},["b"]="n",["sk"]={["base"]="83A3BF",["horns"]="6486BF",["nails"]="BFBFBF",["eye"]="FF0000",["eye_lid"]="499438",["snout"]="417F21",["eye_white"]="000000"},["sz"]="1.0824",["h"]=1,["g"]="m",["r"]="t"}
strength=210
dexterity=210
constitution=300
psyche=150
spirit=150
base_damage_melee=230
damage_resist_melee=4500
damage_resist_fire=4500
damage_resist_frost=4500
damage_resist_mystic=4500
damage_resist_death=4500
profession=2
ai_package=example

[ENTRY]
ID=3693
level=50
display_name=Undead Miner
sub_name=Servant of Abidan
creature_category=Unliving
rarity=1
appearance=c2:{["a"]=[{["type"]="Item-1hAxe-MiningPick",["node"]="left_hand",["colors"]=["3F3F3F","6A3618"]}],["c"]={["boots"]={["type"]="Armor-Light-Low2",["colors"]=[]},["chest"]={["type"]="Armor-Light-Low2",["colors"]=[]},["arms"]={["type"]="Armor-Light-Low2",["colors"]=[]},["leggings"]={["type"]="Armor-Light-Low2",["colors"]=[]},["collar"]={["type"]="Armor-Light-Low2",["colors"]=[]},["belt"]={["type"]="Armor-Light-Low2",["colors"]=[]},["gloves"]={["type"]="Armor-Light-Low2",["colors"]=[]}},["b"]="n",["sk"]={["base"]="7CBF80",["horns"]="6486BF",["nails"]="BFBFBF",["eye"]="FF0000",["eye_lid"]="499438",["snout"]="417F21",["eye_white"]="000000"},["sz"]="1.0824",["h"]=1,["g"]="m",["r"]="t"}
strength=220
dexterity=210
constitution=310
psyche=150
spirit=150
base_damage_melee=235
damage_resist_melee=4500
damage_resist_fire=4500
damage_resist_frost=4500
damage_resist_mystic=4500
damage_resist_death=4500
profession=2
ai_package=example

[ENTRY]
ID=3694
level=49
display_name=Stolen Corpse
sub_name=Servant of Abidan
creature_category=Unliving
rarity=1
appearance=n4:{["a"]=[{["type"]="Item-Bucket",["node"]="left_hand",["colors"]=["940D0D","940D0D","BFBF9F"]},{["type"]="Item-Claw-Basic1",["node"]="right_hand",["colors"]=["71856E","EBAF20","652C2C","816F2B"]}],["c"]="Horde-Zombie",["sk"]={["bone"]="C7B29D",["skin"]="7FAEB8",["blood"]="B03A22",["pants"]="AA8F41",["shirt"]="554704",["detail"]="5F617A",["hair"]="716664"},["sz"]="1.15"}
strength=200
dexterity=225
constitution=285
psyche=150
spirit=150
base_damage_melee=250
damage_resist_melee=4000
damage_resist_fire=4000
damage_resist_frost=4000
damage_resist_mystic=4000
damage_resist_death=4000
profession=2
ai_package=example

[ENTRY]
ID=3695
level=50
display_name=Stolen Corpse
sub_name=Servant of Abidan
creature_category=Unliving
rarity=1
appearance=n4:{["a"]=[{["type"]="Item-Bucket",["node"]="left_hand",["colors"]=["940D0D","940D0D","BFBF9F"]},{["type"]="Item-Claw-Basic1",["node"]="right_hand",["colors"]=["71856E","EBAF20","652C2C","816F2B"]}],["c"]="Horde-Zombie",["sk"]={["bone"]="C7B29D",["skin"]="7CBF80",["blood"]="B03A22",["pants"]="AA8F41",["shirt"]="554704",["detail"]="5F617A",["hair"]="716664"},["sz"]="1.15"}
strength=205
dexterity=230
constitution=290
psyche=150
spirit=150
base_damage_melee=255
damage_resist_melee=4000
damage_resist_fire=4000
damage_resist_frost=4000
damage_resist_mystic=4000
damage_resist_death=4000
profession=2
ai_package=example

[ENTRY]
ID=3696
level=50
display_name=Murdered Foreman
sub_name=Servant of Abidan
creature_category=Unliving
rarity=1
appearance=c2:{["a"]=[{["type"]="Item-2hAxe-Medium3",["node"]="right_hand"}],["c"]={["boots"]={["type"]="Armor-Cloth-Male-Casual2",["colors"]=[]},["chest"]={["type"]="Armor-Cloth-Male-Casual2",["colors"]=["6a5928","9f5147","74756d","f8e69e","634930","989960","fcfefb","36454a"]},["leggings"]={["type"]="Armor-Cloth-Male-Casual2",["colors"]=[]},["belt"]={["type"]="Armor-Cloth-Male-Casual2",["colors"]=[]},["collar"]={["type"]="Armor-Cloth-Male-Casual2",["colors"]=[]},["arms"]={["type"]="Armor-Cloth-Male-Casual2",["colors"]=[]}},["b"]="n",["sk"]={["hair"]="696A7F",["leg_patches"]="517F7F",["chest_patch"]="7A7C94",["tusks"]="C8BBA5",["eye_white"]="ADADAD",["nails"]="63594E",["base"]="6EAA72",["inner_ear"]="606394",["eye"]="B18B65",["eye_brows"]="8BAAAA",["snout"]="6F6152",["arm_patches"]="7491AA"},["sz"]="1.15",["h"]=0,["g"]="m",["r"]="k"}
strength=250
dexterity=230
constitution=325
psyche=150
spirit=150
base_damage_melee=255
damage_resist_melee=4700
damage_resist_fire=4700
damage_resist_frost=4700
damage_resist_mystic=4700
damage_resist_death=4700
profession=2
ai_package=example

[ENTRY]
ID=3697
level=49
display_name=Skeletal Digger
sub_name=Servant of Abidan
creature_category=Unliving
rarity=1
appearance=n4:{["a"]=[{["type"]="Item-Shovel",["node"]="right_hand"},{["type"]="Item-Shield-Medium6",["node"]="left_hand",["colors"]=["3F3F3F","E90000","FFFD00"]}],["c"]="Horde-Skeleton",["sk"]={["bone"]="000000",["armor"]="940000",["trim"]="CD924E",["metal"]="000000",["loincloth"]="7F7F7F",["straps"]="000000"},["sz"]="1.1"}
strength=225
dexterity=200
constitution=300
psyche=150
spirit=150
base_damage_melee=235
damage_resist_melee=4000
damage_resist_fire=4000
damage_resist_frost=4000
damage_resist_mystic=4000
damage_resist_death=4000
profession=2
ai_package=example

[ENTRY]
ID=3699
level=49
display_name=Sheol Tunneler
sub_name=Servant of Abidan
creature_category=Unliving
rarity=1
appearance=n4:{["a"]=[{["type"]="Item-1hMace-High4",["colors"]=["997208","656363","361D04"],["effect"]="Par-WE-1hMace-Blue",["node"]="right_hand"},{["type"]="Item-1hSword-High4",["node"]="left_hand"}],["c"]="Horde-Skeleton-Golgothan",["sk"]={["bone"]="6A6A6A",["trim"]="3F353F",["metal"]="3941BF",["loincloth"]="626262",["helm"]="111115",["eye"]="FF0000",["shirt"]="8CAA8E",["leather"]="2A1C10"},["sz"]="1.1"}
strength=210
dexterity=230
constitution=300
psyche=150
spirit=150
base_damage_melee=240
damage_resist_melee=4000
damage_resist_fire=4000
damage_resist_frost=4000
damage_resist_mystic=4000
damage_resist_death=4000
profession=2
ai_package=example

[ENTRY]
ID=3670
level=50
display_name=Sheol Tunneler
sub_name=Servant of Abidan
creature_category=Unliving
rarity=1
appearance=n4:{["a"]=[{["type"]="Item-1hMace-High4",["colors"]=["997208","656363","361D04"],["effect"]="Par-WE-1hMace-Blue",["node"]="right_hand"},{["type"]="Item-1hSword-High4",["node"]="left_hand"}],["c"]="Horde-Skeleton-Golgothan",["sk"]={["bone"]="6A6A6A",["trim"]="3F353F",["metal"]="3941BF",["loincloth"]="626262",["helm"]="111115",["eye"]="FF0000",["shirt"]="8CAA8E",["leather"]="2A1C10"},["sz"]="1.1"}
strength=210
dexterity=230
constitution=300
psyche=150
spirit=150
base_damage_melee=240
damage_resist_melee=4000
damage_resist_fire=4000
damage_resist_frost=4000
damage_resist_mystic=4000
damage_resist_death=4000
profession=2
ai_package=example

[ENTRY]
ID=3698
level=50
display_name=Skeletal Digger
sub_name=Servant of Abidan
creature_category=Unliving
rarity=1
appearance=n4:{["a"]=[{["type"]="Item-Shovel",["node"]="right_hand"},{["type"]="Item-Shield-Medium6",["node"]="left_hand",["colors"]=["3F3F3F","E90000","FFFD00"]}],["c"]="Horde-Skeleton",["sk"]={["bone"]="000000",["armor"]="000000",["trim"]="3F353F",["metal"]="BF0000",["loincloth"]="7F1100",["straps"]="940000"},["sz"]="1.1"}
strength=230
dexterity=210
constitution=305
psyche=150
spirit=150
base_damage_melee=240
damage_resist_melee=4100
damage_resist_fire=4100
damage_resist_frost=4100
damage_resist_mystic=4100
damage_resist_death=4100
profession=2
ai_package=example

[ENTRY]
ID=3671
level=49
display_name=Mummified Necromancer
sub_name=Servant of Abidan
creature_category=Unliving
rarity=1
appearance=n4:{["a"]=[{["type"]="Item-Staff-Epic4",["colors"]=["6D4903","DBC27F","E1DAAC"],["effect"]="Par-WE-Spear-Death",["node"]="right_hand"}],["c"]="Horde-Mummy_Darkmage",["sk"]={["hair"]="41435A",["base"]="7E6954",["eyes"]="9D0A0E",["armor"]="CD9447",["tattoos"]="662D91",["nose"]="362F2D",["trim"]="3F353F"},["sz"]="1.1"}
strength=150
dexterity=150
constitution=300
psyche=225
spirit=225
base_damage_melee=200
damage_resist_melee=3750
damage_resist_fire=3750
damage_resist_frost=3750
damage_resist_mystic=3750
damage_resist_death=3750
profession=2
ai_package=example

[ENTRY]
ID=3672
level=50
display_name=Mummified Necromancer
sub_name=Servant of Abidan
creature_category=Unliving
rarity=1
appearance=n4:{["a"]=[{["type"]="Item-Staff-Epic4",["colors"]=["6D4903","DBC27F","E1DAAC"],["effect"]="Par-WE-Spear-Death",["node"]="right_hand"}],["c"]="Horde-Mummy_Darkmage",["sk"]={["hair"]="41435A",["base"]="7E6954",["eyes"]="9D0A0E",["armor"]="CD9447",["tattoos"]="662D91",["nose"]="362F2D",["trim"]="3F353F"},["sz"]="1.1"}
strength=150
dexterity=150
constitution=300
psyche=225
spirit=225
base_damage_melee=200
damage_resist_melee=3750
damage_resist_fire=3750
damage_resist_frost=3750
damage_resist_mystic=3750
damage_resist_death=3750
profession=2
ai_package=example

[ENTRY]
ID=3673
level=50
display_name=Stagnant Air
sub_name=
creature_category=Unliving
rarity=1
appearance=n4:{["sk"]={["armor"]="552E47",["main2"]="23232A",["main"]="3F3F3F",["eye"]="D20003",["main3"]="111115",["armor_marking"]="4008BA"},["c"]="Horde-Elemental_Air",["sz"]="1.1"}
strength=150
dexterity=150
constitution=300
psyche=250
spirit=225
base_damage_melee=215
damage_resist_melee=3750
damage_resist_fire=3750
damage_resist_frost=3750
damage_resist_mystic=3750
damage_resist_death=3750
profession=2
ai_package=example

[ENTRY]
ID=3674
level=50
display_name=Life Ember
sub_name=
creature_category=Unliving
rarity=1
appearance=n4:{["sk"]={["fire6"]="FF0000",["base"]="56471A",["fire1"]="DF4B00",["fire3"]="FF8827",["eye"]="FFFFFF",["fire2"]="FF5E06",["fire5"]="FF0000",["fire4"]="FF0000"},["c"]="Horde-Elemental_Fire",["sz"]="1.1"}
strength=150
dexterity=150
constitution=300
psyche=250
spirit=225
base_damage_melee=215
damage_resist_melee=3750
damage_resist_fire=3750
damage_resist_frost=3750
damage_resist_mystic=3750
damage_resist_death=3750
profession=2
ai_package=example

[ENTRY]
ID=3675
level=49
display_name=Subterranean Crawler
sub_name=
creature_category=Unliving
rarity=1
appearance=n4:{["sk"]={["eyeball"]="EB9B7F",["rock"]="7F5632",["dark_rock"]="403733",["iris"]="417371"},["c"]="Horde-Stalagmite",["sz"]="1.15"}
strength=200
dexterity=230
constitution=300
psyche=150
spirit=150
base_damage_melee=225
damage_resist_melee=4000
damage_resist_fire=4000
damage_resist_frost=4000
damage_resist_mystic=4000
damage_resist_death=4000
profession=2
ai_package=example

[ENTRY]
ID=3676
level=49
display_name=Subterranean Crawler
sub_name=
creature_category=Unliving
rarity=1
appearance=n4:{["sk"]={["eyeball"]="EB9B7F",["rock"]="687F7F",["dark_rock"]="403733",["iris"]="417371"},["c"]="Horde-Stalagmite",["sz"]="1.15"}
strength=200
dexterity=230
constitution=300
psyche=150
spirit=150
base_damage_melee=225
damage_resist_melee=4000
damage_resist_fire=4000
damage_resist_frost=4000
damage_resist_mystic=4000
damage_resist_death=4000
profession=2
ai_package=example

[ENTRY]
ID=3677
level=49
display_name=Krostakin
sub_name=Servant of Abidan
creature_category=Unliving
rarity=1
appearance=n4:{["sk"]={["blend"]="7F7F7F",["base"]="3F2A21",["tip"]="2A0000",["highlight"]="000000"},["c"]="Horde-Krostakin",["sz"]="2"}
strength=150
dexterity=150
constitution=300
psyche=220
spirit=250
base_damage_melee=225
damage_resist_melee=4000
damage_resist_fire=4000
damage_resist_frost=4000
damage_resist_mystic=4000
damage_resist_death=4000
profession=2
ai_package=example

[ENTRY]
ID=3678
level=50
display_name=Krostakin
sub_name=Servant of Abidan
creature_category=Unliving
rarity=1
appearance=n4:{["sk"]={["blend"]="7F2B07",["base"]="000000",["tip"]="2A0000",["highlight"]="150E05"},["c"]="Horde-Krostakin",["sz"]="2"}
strength=150
dexterity=150
constitution=300
psyche=220
spirit=250
base_damage_melee=225
damage_resist_melee=4000
damage_resist_fire=4000
damage_resist_frost=4000
damage_resist_mystic=4000
damage_resist_death=4000
profession=2
ai_package=example

**Comment by rockfireredmoon** [comment]
All done. Follow spawn packages added :-

```
[ENTRY]
Name=50_maw_Anexima
Spawn=7816,100  ;Anexima (50)

[ENTRY]
Name=50_maw_Drakkar
Spawn=7817,100  ;Drakker Zol (50)

[ENTRY]
Name=50_maw_Valkalth
Spawn=7818,100  ;Valkalth (50)

[ENTRY]
Name=50_maw_Karayan
Spawn=7819,100  ;Karayan (50)

[ENTRY]
Name=50_maw_Braakurk
Spawn=7820,100  ;Karayan (50)

[ENTRY]
Name=50_maw_Mix1
Spawn=7821,100  ;Undead Miner (50)
Spawn=7822,100  ;Undead Miner (50)
Spawn=7823,100  ;Stolen Corpse (49)
Spawn=7824,100  ;Stolen Corpse (50)
Spawn=7825,100  ;Murdered Foreman (50)
Spawn=7826,100  ;Skeletel Digger (49)
Spawn=7827,100  ;Sheol Tunneler (49)
Spawn=7828,100  ;Sheol Tunneler (50)
Spawn=7829,100  ;Skeletel Digger (50)
Spawn=7830,100  ;Mummified Necromancer (49)
Spawn=7831,100  ;Mummified Necromancer (50)

[ENTRY]
Name=50_maw_Mix2
Spawn=7832,100  ;Stagnant Air (50)
Spawn=7833,100  ;Life Ember (50)
Spawn=7834,100  ;Subterranean Crawler (49)
Spawn=7835,100  ;Subterranean Crawler (49)
Spawn=7836,105  ;Krostakin (49)
Spawn=7837,105  ;Krostakin (50)
```
