### ISSUE TITLE
"Piece of the Puzzle" is parented by an unknown quest

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#441]
While looking at some WE issues I noticed that quest 941, "Piece of the Puzzle" has quest 940 as it's requirement. However no such quest exists. 

Investigate whether it did exist, and if so re-instate it. If there is not supposed to be a requirement for this quest, remove it.

**Comment by rockfireredmoon** [comment]
Was caused by the WE quest corruption.

**Comment by LiskaQuicksilver** [comment]
This was fixed.
