### ISSUE TITLE
wearing Vampire Skull Helmet prevents movement

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#452]
Reported By: Rivers Slypaw
Category: ECON

The Vampire Skull Helmet in the starting grove Beata Beast Box, when equiped, it makes you invisable and you cannot move.

**Comment by LiskaQuicksilver** [comment]
Tested this in the reverted Mushroom Isle. Helmet appears normally and the player can move just fine. Presumed fixed.
