### ISSUE TITLE
Beta Beast Box - Tokens vs Essence wording conflict

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#453]
Reported By: Rivers Slypaw
Category: ECON

you are given tokens to buy items from the Beta Beast Box, however if you have 0, it tells you that you do not have enough essences. It should say you don't have enough tokens.

**Comment by rockfireredmoon** [comment]
I have moved this to R11, as this needs testing again anyway now the pre-event mushroom isle is active.

**Comment by LiskaQuicksilver** [comment]
Tested. This issue still stands.

**Comment by rockfireredmoon** [comment]
Fixed

**Comment by LiskaQuicksilver** [comment]
Verified changed.
