### ISSUE TITLE
Hide And Seek-Missing Quest Complete Text (Nante's Waystation/Dustshore)

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#455]
Reported By: Dax Orillion
Category: CHAR

On turning in the quest it only displays "Return to Mork Duststomper" as opposed to :
"You have proven yourself a TRUE adventurer! 

Take this key to my Adventurer Chest. You may only take one item, so choose wisely! 

Safe journeys, friend! 
" 
(Per the wiki)

**Comment by LiskaQuicksilver** [comment]
Ack. Another one.

**Comment by LiskaQuicksilver** [comment]
Tested and is confirmed to be fixed on the test server. Likely associated with the asset deletion bug recently resolved in the World Editor.
