### ISSUE TITLE
Mushroom Isle's original BGM needs to be reactivated.

### ISSUE THREAD

**Issue by LiskaQuicksilver** [rockfireredmoon/iceee#459]
When Mushroom Isle was reverted from the Valkal's Shadow event version, the original BGM "Newbiebox" was not restored and was instead replaced with the BGM tracks from Anglorum, etc.

**Comment by rockfireredmoon** [comment]
Fixed.

**Comment by LiskaQuicksilver** [comment]
This is fixed.
