### ISSUE TITLE
Players are starting the game as Pink Shroomies?

### ISSUE THREAD

**Issue by LiskaQuicksilver** [rockfireredmoon/iceee#463]
This was reported on Discord by a player who claimed they were a Pink Shroomie when logging into the game for the first time. The player claimed as soon as the they got ingame, their character was not what they had made, the appearance being replaced by a Pink Shroomie. Further they were unable to interact with anything and cannot progress because of it.

Please investigate this issue as it seems something many not be saving the players' appearances on character creation. Possibly related to the earsize/tailsize issue that was fixed, but, could be something else entirely.

**Comment by rockfireredmoon** [comment]
Fixed. Root cause was missing HTTPChecksum.txt. See #467

**Comment by rockfireredmoon** [comment]
PS. Player account fixed.
