### ISSUE TITLE
Cumulative List for the Buff/Timer Bug

### ISSUE THREAD

**Issue by LiskaQuicksilver** [rockfireredmoon/iceee#469]
The following skills were tested in the hopes of verifying if the Buff/Timer Bug has been fixed. While greatly incomplete, here are my results. I am creating this new issue to bring all the previous bug reports together in one list.

XP Tome: Works as intended, persists across zones without a sudden timer drop. Tome does pause it's timer when the player logs out and then resumes when the player logs back in later. Seems to break speed buffs however when it expires.

Bounder Dash: Sort of works. It expires as it should under normal conditions; however, changing zones such as entering an instance still breaks the timer (a 7 min remaining timer changed to approx. 24855days, 3hours, 10minutes, 13seconds). Can be overridden by the admin speed buff but this gets negated when BD expires as it supposed to.

Unstick: Seems to work even as a buff expires. Needs more testing.

Can Opener: Seems to work and expire when it's duration is up.

Disarm: Seems to work, but, lacking a visible timer, it's hard to tell.

Reflective Ward: Works and persists across zones without a sudden timer drop. Negates the admin speed buff when it expires. Expires normally and doesn't seem to glitch or break.

Taurian Might: Works and persists across zones without a sudden timer drop. Negates the admin speed buff when it expires.  Expires normally and doesn't seem to glitch or break.

Warrior Spirit: Works and persists across zones without a sudden timer drop. Negates the admin speed buff when it expires. Expires normally and doesn't seem to glitch or break.

Turtle: Works and persists across zones without a sudden timer drop. Negates the admin speed buff when it expires. Expires normally and doesn't seem to glitch or break.

Form of the Wolf Transformation Potion: Works as intended. Expires normally and doesn't seem to glitch or break.

Morass: Seems to work (was previously broken, presumed fixed), expires normally.

Portal: Stonehenge: Works normally and did not affect any active buffs when porting to Anglorum (Stonehenge) using this skill.

Mystic Missile: Seems to work normally though hard to tell on a 20 second timer.

Frost Spear: Tested via enemy use only. Appears to work as intended in spite of it's 20 second timer.

Stun: Tested via enemy use. Appears to work as intended, but, lacking a visible timer, it's hard to tell.

Feline's Grace: Tested via enemy use only. Appears to work, but, needs more testing.

Healing Hand:  Seems to work even as a buff expires.

Healing Tendril: Seems to work even as a buff expires.

**Comment by rockfireredmoon** [comment]
All done except anything that negates admin speed buffs. These are treated differently and we can live with any problems.

**Comment by LiskaQuicksilver** [comment]
It is with great pleasure that I close this issue as it seems we have FINALLY crushed this bit of a headache of a massive bug after a good three years.
