### ISSUE TITLE
bug: Quest Giver- Join the Lightkeepers guild (Fort Stonehenge)

### ISSUE THREAD

**Issue by HulkCougarstein** [rockfireredmoon/iceee#47]
A gold crown is visible on the small inset map and when moused over says (quest giver, join the lightkeepers guild).  When the player goes to where this quest is, it is located atop of the NPC Graynard Birk, however the NPC does not have a crown atop of itself and thus the quest is unable to be accepted.

In fairness at the time I noticed this inconsistency I was lv 43 so maybe a lv 10-13 character there is no issue as perhaps its part of a step-up quest pattern.  However irregardless, being its a future quest then the giving NPC should have a greyed circular exclamation point atop its head; or so I feel.

**Comment by Heathendel** [comment]
That is my bad, that is the guild prototype quest giver, guilds are a
feature we will be adding the quest is deactivated right now
It's not a step up guild just testing the guild system we developed

**Comment by rockfireredmoon** [comment]
I've deactivated the quest completely for now. Fixed.
