### ISSUE TITLE
Completely new accounts and characters never get daily rewards

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#473]

**Comment by rockfireredmoon** [comment]
Fixed. Anyone affected by this bug will be credited 1000 credits.

**Comment by LiskaQuicksilver** [comment]
Okay, tested on the test server with a fresh account and a fresh character. Although the timing of the Rewards may be off a little (that needs more testing), the new account + character does get them, so we'll presume this is fixed for now.
