### ISSUE TITLE
Additional Groves have Build issues

### ISSUE THREAD

**Issue by LiskaQuicksilver** [rockfireredmoon/iceee#477]
This was reported by Feral (Lightning King). Apparently he was unable to properly build in his second grove even though his original grove was just fine. Things such as being unable to set environments and spawn points anywhere save in one certain spot in the grove were listed as some of the problems encountered.

**Comment by rockfireredmoon** [comment]
This appears to be a permissions problem, and can currently be worked around using /SetAdmin. It was introduced when terrain editing was opened. 

To fix this, I will be separating the grove permissions so terrain editing, creature tweaking, grove editing etc can all be specified separately.

**Comment by rockfireredmoon** [comment]
Fixed. The following permissions were already referred to in the client source :
- dev
- tweakScreens
- setappearance
- version
- rassemble
- playSound
- compositor
- debug
- build
- scriptTest
- importAbilities
- groveBuild
- worldBuild

I will not go into details of what each is, but the ones of interest here are the 'build', 'groveBuild', 'worldBuild' ones.

Which of these client permissions a client gets is now sent by the server as a response to the clientperms.list query. 

Each user may be in one of four logical roles, determined by their account permissions.

- Administrator - Can do everything, gets all client permissions.
- Sage - Can do everything a player can, plus gets set speed permission setappearance
- User - Ordinary user. Only gets build and groveBuild client  permissions
- Developer - Gets additional developer commands (terrain editing).

Addtional server side permissions act as before, but are now also available to the client to perform validation of actions where needed. 

- Tweakers - Can use tweak tools. Gets tweakScreens client permission.
- Debug - Gets additional debug commands.

So testing will involve setting up (or using existing) users that are each of these general roles.  Specifically for build permission testing ..

- Administrator should be able to do anything including world edits
- Sages and ordinary users may edit only their groves (I Might allow Sages to edit others groves)
- Developers can do world edits but not grove edits
- Users can only edit their own groves

**Comment by LiskaQuicksilver** [comment]
Hokay, I'm unsure if this was done previously or not, but, for some reason both my admin account and the one that supposed to have been my test player account, TestKitsu, both appear to have Administrator permissions. Please verify and fix if you can. It's entirely possible you might have accidentally set all accounts on the VS test server to administrator at some point.

**Comment by LiskaQuicksilver** [comment]
Emerald and I have tested most combinations of these four account types. All appear working as intended for now. Closing issue.
