### ISSUE TITLE
bug/adjustment: Transformation travel spell

### ISSUE THREAD

**Issue by HulkCougarstein** [rockfireredmoon/iceee#48]
In the past (this being prior to the repair of being stuck in transformed mode) one couldn't use their meelee attack ability (1 button ) while in transformation mode, (however they could meelee attack with arrows/wands via the 2 button ).  

Now one is able to attack in transformation mode as if they were their standard character and all attacks/abilities function normally as if not transformed at all.

**Comment by Heathendel** [comment]
That was actually always the case least for me it's a bug yes but weren't
to worries about since this is a temporary mount system but we are aware of
that thank you

**Comment by rockfireredmoon** [comment]
Fixed. As soon as player enters combat, transformation will be removed as was intended.
