### ISSUE TITLE
bug: (causing the server crashes) Transformation spell in conjunction with blue portal

### ISSUE THREAD

**Issue by HulkCougarstein** [rockfireredmoon/iceee#49]
3 times today the server crashed on account of a world-reentry bug.  After exiting a dungeon back into the world the client will say 'entering Anglorum' , 'entering Europe' etc.... however it seems that if your transformed into a travel animal and exit into the world this will crash the client/server.

**Comment by rockfireredmoon** [comment]
Fixed
