### ISSUE TITLE
Unused Boss Fengarian Has Lost His Appearance

### ISSUE THREAD

**Issue by LiskaQuicksilver** [rockfireredmoon/iceee#495]
Noticed last night while in my grove that the unused Dragon mob Fangarian had lost his model and was now appearing in game as a Pink Shroomie. I suspect this was due to the World Editor bug that was fixed some weeks ago that had caused asset corruption in the Git database. Likely more residual items that had been missed when we cleaned up that mess.

**Comment by rockfireredmoon** [comment]
Fixed. Appearance went missing with commit https://github.com/rockfireredmoon/iceee/commit/4c000d3d43d5e302c27c8c476297ab4673c535a7#diff-6efb50c45f2d20c0f7f28b267e9b392f (yes, probably WE bug)

**Comment by LiskaQuicksilver** [comment]
Em, I hate to say this, but, Fengarian's appearance isn't correct. The appearance you gave to him belongs to Valkara. Fengarian's true appearance was that Red Dragon model. Please fix again. If need be use the size currently given but add in Mini-Fengarian's appearance instead.

**Comment by LiskaQuicksilver** [comment]
Edit: I "MIGHT" have accidentally fixed this one myself while testing the Grove permissions. Please verify that you can see a Red Dragon (the model was simply 'Dragon' btw) when spawning him.

**Comment by rockfireredmoon** [comment]
Have moved this edited appearance to be permanent. Heath can argue it later if we have gone against his intentions.

**Comment by LiskaQuicksilver** [comment]
Verified fixed up. Closing issue.
