### ISSUE TITLE
Ezra Greyun Quest Shoulder Rewards Broken

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#508]
Reported By: Galen Jarrus
Category: ECON

The rewards from the last Greysun quest from Councilor Willowbeard seem to be broken model-wise . At the very least the Greysun Pauldron item seems either to be missing textures or is rendering flipped.  Might suggest double-checking the rest of the shoulder items in the available rewards just to be safe.

**Comment by rockfireredmoon** [comment]
Fixed. Two of the items were using Right instead of Left should (without setting an attachment point). 

900073  was broken
900071 was broken
900074 was OK
900072 was OK

**Comment by LiskaQuicksilver** [comment]
Fixed.
