### ISSUE TITLE
Implement min. health

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#510]
It would be very useful to have a minimum health stat for immortal characters, such as stage 1 of Valkal. We could avoid unreliable percentage health barrier in the script.

**Comment by rockfireredmoon** [comment]
Added. A new stat is available min_health_pc that is now used by the first Valkal creature def. It is set at 5%. It should now be impossible for Health to go below this. The script barrier is left at 10%.

**Comment by LiskaQuicksilver** [comment]
Valkal phase 1 has been tested and confirmed fixed.
