### ISSUE TITLE
One item becoming another

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#512]
Reported By: Raptec Clawtooth
Category: ECON

When i was playing at first ,  in one dungeon, (i dont remember which) 
 I receive the blueprints to do this item:
Night Owl Gloves 
Lvl 23
HANDS    <----(This is important)
Armor: 84

So, veeery later i manage to recollect all items necesary for their creation:
8 light  waves   4 Rouge gems and 8 of that red nylon (i forget their name)

The thing is when i crafted  in Canterlot i have the EXACTS material, 
but then the Gloves become a CHEST equipment
so i end with this item:

Night Owl GLOVES  (it even have their gloves  picture)
Level 23
CHEST   <-------  !!!
Armor:84
+6 Constitution
+ Psyche
+5 Spirit
if sold  it give 27 Silver  and 29 copper

I take two screenshots of this,  were i can send to show  it?

**Comment by rockfireredmoon** [comment]
Fixed. Was wrong equip type (using 11 instead of 13). It appears this has always been incorrect,  so presumably was incorrect in SPM days too.

**Comment by LiskaQuicksilver** [comment]
Verified fixed on VS test server.
