### ISSUE TITLE
Credit shop armor item preiews blank

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#513]
Reported By: Queen Hogg
Category: UI

the following items in the credit shop do not have a preview, only a blank white image. 

Entire Dark Knight set

Crystal Pauldrons

**Comment by LiskaQuicksilver** [comment]
This issue is known. We just haven't gotten around to fixing it.

**Comment by rockfireredmoon** [comment]
Fixed

**Comment by LiskaQuicksilver** [comment]
Confirmed fixed.
