### ISSUE TITLE
Posible missing items from Ritual of the mist

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#521]
Reported By: Queen Hogg
Category: QUEST

Amaren Mor says ti take one of these items but there is only 1 item to take: Spiderward ring. 
Either there are missing items or it's just worded incorectly.

**Comment by rockfireredmoon** [comment]
Fixed. Changed wording of quest text.

**Comment by LiskaQuicksilver** [comment]
Verified fixed.
