### ISSUE TITLE
Weather system can still cause crashes.

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#523]
A crash can occur when instances flushed. The trace is the same every time.

**Comment by rockfireredmoon** [comment]
Fixed. Also fixed issue where if weather is active, and you logout and login again and return to the same character in the same zone, weather will not start again until its next change.

**Comment by LiskaQuicksilver** [comment]
Have had no crashes in at least six weeks. This is presumed fixed. Closing.
