### ISSUE TITLE
Bug: AI mechanics - Spitterskrill in Junderland

### ISSUE THREAD

**Issue by HulkCougarstein** [rockfireredmoon/iceee#57]
The spitterskrill in Junderland have some wonky AI mechanics,  For comparison and reference I will compare them to the Drowned Zombies in the Moors of Anglorum since both of these creatures shoot soul needles, 

The drowned zombie-- It will keep its distance firing soul needles at the player from a distance, 

Spitterskrill in Junderland-- It has an AI in which the spitterskrill will stand still and attack at first from a distance, then once the magic attack starts moving towards the player the skrill will take a given amount of steps towards the player and then stand and attack again repeating the script.  However, should the player moves forward towards the spitterskrill and be within about 20meters of it while its soul needles attack is in motion towards the player then the spitterskrill will run towards and bypass the player, moonwalk till the run duration of its AI scripting is finished and then finally autocorrect to stand in front of the player.

**Comment by rockfireredmoon** [comment]
I couldn't see this exact behavior, but all the same converted the AI script to the new Squirrel system anyway. Please retest this.
