### ISSUE TITLE
Backdoor access to Swineland

### ISSUE THREAD

**Issue by LiskaQuicksilver** [rockfireredmoon/iceee#58]
Essentially, if the player climbs over the mountains near the far eastern Sanctuary, they can end up falling into the river between Grunes Tal, Swineland and Frost Peak. In doing this, the player can easily bypass the barrier blocking access to Swineland by taking a southern 'backdoor' route up through the snow region all the way up to just south of the 'dam-like blockade'. From there, all the player has to do is follow the invisible barrier until it terminates.

I think this needs fixing ASAP.

**Comment by Rictar-Gasper** [comment]
i sealed it
