### ISSUE TITLE
Query:- Form of Cougar

### ISSUE THREAD

**Issue by HulkCougarstein** [rockfireredmoon/iceee#59]
I was looking at the coding page https://github.com/rockfireredmoon/iceee/commit/83fbebe7804c047694c00156c41cba441f7d1df2 and the Form of Cougar code seems a tad different than the others (possible issue?)

If you look at the code you will notice a difference, here is a summation

Line 1010 - form of cougar

-"27004" "Form Of The Cougar" "-1" "3000" "WolfSpiritWarmup" "0" "0" "MovementSpeed" "2000" "NotStatus(IN_COMBAT),NotSilenced(),InRange(150.0),Will(5)" "onActivate:Self:Transform(7812),Add(MOD_MOVEMENT,50,600);onDeactivate:Self:Untransform(),DisplayEffect("HealingPotion")" "HealingPotion" "3" "20,,,()," "Icon-32-Ability-K_Hatred.png|Icon-32-BG-Red.png" 

and from another travel magic spell form of wolf Line 1009

-"27003" "Form Of The Wolf" "-1" "3000" "WolfSpiritWarmup" "0" "0" "MovementSpeed" "2000" "NotStatus(IN_COMBAT),NotTransformed(),NotSilenced(),InRange(150.0),Will(5)" "onActivate:Self:Transform(7811),Add(MOD_MOVEMENT,50,600);onDeactivate:Self:Untransform(),DisplayEffect("HealingPotion")" "HealingPotion" "3" "20,,,()," "Icon-32-Ability-D_Wolf_Spirit.png|Icon-32-BG-Red.png" "Transform into a feral form and increase Movement Speed by 50% for 10 minutes." "Travel" "30" "30" "43" "Buff" "1" "0" "0" "0" "0" "+/BuffMove/Buff:Run Speed" "Friend Alive"

you will notice that Form of Wolfs code has (IN_COMBAT),NotTransformed(),NotSilenced() but Form of Cougars code is (IN_COMBAT),NotSilenced()

the Not Transformed part of the code is missing , I think that this is causing one whom is turned into a cougar/lion when hit by enemy fire to transform back into ones regular character.

**Comment by rockfireredmoon** [comment]
That is a bug, but NotTransformed() is pre-condition for transforming. So the ommission of this would allow you to be transformed twice! Sort of. The removing transformation for combat is intentional, as we do not want speed advantage in combat.
