### ISSUE TITLE
Swineland Mobs

### ISSUE THREAD

**Issue by Heathendel** [rockfireredmoon/iceee#6]
Hey Em i noticed that the additional Swineland mobs i sent you were not added to the Dev server but it had said in the previous version of issue tracker that they were.  Im not sure if you were aware of this or if something may have just gone wrong while adding them so i thought id mention it.  Hopefully you still have the Entries i sent, if not ill remake them.

**Comment by rockfireredmoon** [comment]
Ill try and get them out of the old issue tracker data, will let you know if they need remaking
