### ISSUE TITLE
Update installer and rebrand Earth Eternal - Scourge Of Abidan

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#74]
The current installer is branded "Planet Forever - ICEEE". Rebrand this to "Earth Eternal - Scourge Of Abidan"

**Comment by Heathendel** [comment]
Indeed we should rebrand the game for sure.  I would also like to have a trailer for viewing BEFORE release doesnt have to spectacular but its something we need done for sure.

**Comment by rockfireredmoon** [comment]
Done. No video yet though, that is going to be considerably more complicated with the current client :) Lets keep that for the Anubian War
