### ISSUE TITLE
boundersday

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#786]
Reported By: Sage Grizzlybearking
Category: IDEA

"(29012.9,508.002,62912.2,9)" cant pick up egg

**Comment by rockfireredmoon** [comment]
Fixed

**Comment by LiskaQuicksilver** [comment]
The Eggs in both Bremen and Heartwood can be collected now. See Issue #511 for problems with the Camelot Eggs.

**Comment by LiskaQuicksilver** [comment]
This issue is fixed now. Closing.
