### ISSUE TITLE
quest ability points  / golden egg quest

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#797]
Reported By: Sage Grizzlybearking
Category: PERF

Quests granting alibity points may not be granting the points.

**Comment by rockfireredmoon** [comment]
Ability points are being granted, but I have made some changes to the Golden Egg Quest.

The Quest Ender is a NEW NPC called **Minister Buckley**. He is standing next to the Big Ben Tower. The reason for using a new NPC is that this avoids a conflict when the level restrictions are re-introduced. Because we use(d) Ambassador Hopps for both the normal level range egg hunt, and the Golden Egg for all players, and the quest system does not 'know' up front about this extended level mechanic, it was not possible for a high level player to run the quest!

Note that this quest is an Account Quest. In that it can only be run once per account. Testers will need to talk to Emerald to get her to remove the quest from your accounts journal if you need to test more than once on the same account.

Also note that you are not given ability points upon quest completion, instead you must open the 'purse' you were given which contains the points.

**Comment by LiskaQuicksilver** [comment]
Okay, Em, much as I hate to say this, by creating a new NPC, you forgot to change the quest target for the Golden Egg quest rendering it untakeable now. I have tested on both my Admin account and Player account on the test server and neither one is being given the quest by the Egg anymore even though the Egg sparkles. Because I cannot take the quest on either account, I cannot test whether or not the new setup is working.

**Comment by rockfireredmoon** [comment]
I did change the quest target. I suspect the problem was that you had already completed it once on both accounts? I have removed the account quest from both of them so you can take it again.

**Comment by LiskaQuicksilver** [comment]
No. My player account had never done the quest and still couldn't take it. I'll retest anyway to at least verify the AP is functional but something else got busted when you changed targets.

**Comment by LiskaQuicksilver** [comment]
Yep. Still cannot take this quest anymore. Don't know what you broke, but, this quest is completely borked.

**Comment by rockfireredmoon** [comment]
Fixed. Try again

**Comment by LiskaQuicksilver** [comment]
Still nothing. Sorry.

**Comment by rockfireredmoon** [comment]
The server was updated. But I now suspect you had the same problem I did. Please retest, but before doing so, use the GM screen to remove quest ID 648. The remove function now ALSO clears out account quests AND character quests. It turned out that the problem I had all last night is I was only ever clearing out the account quest (thinking thats all that was needed). Now you do this yourself using the usual method.

**Comment by LiskaQuicksilver** [comment]
Alright, I'll retest, but, just so you know, my player account still couldn't take it either. I made sure to check.

**Comment by LiskaQuicksilver** [comment]
Okay, just tested your suggestion. Still not working.

**Comment by LiskaQuicksilver** [comment]
Took us a few tries but this is working again and the reward item is now actually giving out the rewards it claims to give.
