### ISSUE TITLE
Credit Shop

### ISSUE THREAD

**Issue by BantamCrow** [rockfireredmoon/iceee#80]
The front page of the log-in screen claims there are items inside the credit shop, but there is nothing when I click on it. Is the credit shop not "public" yet? I would definitely love to support this game.

**Comment by LiskaQuicksilver** [comment]
The Credit Shop is indeed not yet public. Em is working to put the finishing touches on the next main server update and the Credit Shop functionality and items are among the new additions. Currently we're still sorting out item pricing among other things. Just be patient and we'll open the CS when it's ready to be rolled out.

**Comment by rockfireredmoon** [comment]
Out-of-date. CS now open.
