### ISSUE TITLE
Ok, Let's plan an event :)

### ISSUE THREAD

**Issue by Rictar-Gasper** [rockfireredmoon/iceee#81]
Em would like an Event For Scourge Of Abidan so lets get planning :)

for the reopening of Grunes itself we can use quite a bit of what we did last time a lot of the elements worked well we just have to tweak a few issues
-A rehearsed speech for the grand opening
-green fog as a prop not a creature
-AI script for spawning the attack waves
-Litch Heath kill-able?

For the rest of it we should probably do a week long event
-first Em's new updated version of the client we have been playing with on the Dev server :) 
-Have some Syschat Broadcast leading up up the event all week long about increased undead activity
-in addition to the main event maybe have a lower lvl event at Camelot for our lowbies, something like the undead coming from from Wilhelm's Crypt  when ever we have enough people on to sustain an event (like Heath did with the dragon)
-maybe some event only quests? (helping the redeemers make TNT?,get supplies for the Redeemers?,quests in Undead areas? )

I am just trying to get the ball rolling any ideas or input you all have would to make this the best event possible :)

**Comment by rockfireredmoon** [comment]
Good idea Ric :) I have added a new client screen that I hope will help with this. It basically lets you spawn creatures without creating spawn points. Give it a creature ID, a number of creatures to spawn, where to place them (randomly or at a prop), their faction, and whether to attack something (using an ability of your choice). Then click 'Spawn' whenever you need more of that creature.

I will look into the other bits like the fog prop and making litch Heath killable.

All the other ideas sound good too.

![selection_018](https://cloud.githubusercontent.com/assets/7688839/9562500/956fba96-4e65-11e5-93c5-8654bf595461.png)

**Comment by rockfireredmoon** [comment]
The "Litch Heath kill-able?" should be taken care of now. I will explain next time in game.

**Comment by rockfireredmoon** [comment]
Moving out of milestone as event didnt happen for Scourge, but likely will at a later time.

**Comment by LiskaQuicksilver** [comment]
Closing as we not only held this event, but are now deep into the next expansion beyond SOA, Valkal's Shadow.
