### ISSUE TITLE
Bounders Day Camelot Emerald Eggs ID mixup

### ISSUE THREAD

**Issue by LiskaQuicksilver** [rockfireredmoon/iceee#825]
While testing the BD Camelot quest for the Eggs, I made the unfortunate discovery that the Emerald Egg asset IDs in Camelot had been mixed up with Petrified Twigs. This somehow got overlooked yesterday when Bear King and I attempted to run the quest.

**Comment by rockfireredmoon** [comment]
Fixed

**Comment by LiskaQuicksilver** [comment]
Confirmed fixed.
