### ISSUE TITLE
Interupted Spellcasting  (Reflective Ward)

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#93]
Reported By: Wake Duskleaf
Category: COMBAT

Spellcasting becoming interpted the moment Reflective Ward wears off. 
Experienced this when casting Soul Needles.

**Comment by rockfireredmoon** [comment]
Reported By: Aureus Seitaro
Category: COMBAT

Anytime a buff or debuff expires from the player, if the plyer is casting any cast time spell, it is immediately and consistently canceled.

This was discovered initiating combat with Frost Spear by myself. I initially thought it may be lag, but one day my Portal: New Badari canceled at 3/4 progress when Reflective Ward died.

I have since confirmed using Torpid Slimers' Wither and my own reflective ward a total of 15 times each using Portal: New Badari as the cast window is much easier to make, but since Frost Spear tipped me off to this issue (and I suspect many of my Cold Snaps hve suffered from this too, causing me many deaths or near deaths), I'm going to call it a universal cast time problem.

**Comment by LiskaQuicksilver** [comment]
This has now been fixed as part of the Buff/Timer bug fixes in VS Maintenance Release 12.
