### ISSUE TITLE
Coastal Cave

### ISSUE THREAD

**Issue by rockfireredmoon** [rockfireredmoon/iceee#98]
Reported By: Marshall Westing
Category: WORLD

In the Avenge Jod's Death quest, once you go into the coastal cave there are two pillars where Magmuh and Magmange are. You can see through parts of the pillars on both sides of the metal plate on the floor.

**Comment by rockfireredmoon** [comment]
Ric, could I assign this one to you? I've taken a look and it does indeed have gaps and look a bit odd. I am sure you could come up with something to fix it :)

**Comment by Rictar-Gasper** [comment]
fixed on the Dev Server you can move it to the main

i dont have /setbuildpermission on the main server

**Comment by Rictar-Gasper** [comment]
fixed on main server
